In [1]:
import pandas as pd
import json
import numpy as np
import matplotlib.pyplot as plt

from UtilsRF import scorer

In [2]:
def print_sentence_relation_subj_obj(data, print_text="predicted"):
    for i, sentence in enumerate(data["token"]):
        print(f"{print_text}: {data.iloc[i][print_text]} (id: {data.iloc[i]['id']})")
        print(
            f"Subject: {data.iloc[i]['token'][data.iloc[i]['subj_start']:data.iloc[i]['subj_end']+1]}"
        )
        print(
            f"Object: {data.iloc[i]['token'][data.iloc[i]['obj_start']:data.iloc[i]['obj_end']+1]}"
        )
        print(f"{' '.join(sentence)}\n")

In [3]:
def summary_relation_FN(dataset, relation, summary_data, not_long=True):
    """
    Given a dataset and a relation, it outputs the sentences where that relation is the correct one and the predicted one is wrong (i.e. TP and FN for that relation).
    It provides some summaries (number of wrong relations, predicted relations, number of sentences with long distance between entities).
    Afterwards, it prints the sentences along with the entities and the predicted relations.
    If not_long is True, it only prints the sentences where the distance between entities is NOT long
    """
    data_relation = test_data[dataset["relation"] == relation]
    print(f"Number of sentences with relation {relation} : {len(data_relation)}")

    data_relation_wrong = data_relation[
        data_relation["relation"] != data_relation["predicted"]
    ]
    print(
        f"Number of sentences with wrong relation {relation} : {len(data_relation_wrong)}"
    )

    data_relation_wrong_not_long = data_relation_wrong[
        data_relation_wrong["entity_distance_categorical"] != "long"
    ]
    print(
        f"Of those sentences, {len(data_relation_wrong) - len(data_relation_wrong_not_long)} have long distance between entities"
    )

    wrong_relations_summary = data_relation_wrong["predicted"].value_counts()
    print(
        f"\nSummary of relations assigned instead of {relation}:\n{wrong_relations_summary}\n"
    )

    print(f"List of (NOT LONG) sentences with relation {relation} wrongly predicted")
    print_sentence_relation_subj_obj(
        data_relation_wrong_not_long if not_long else data_relation_wrong,
        print_text="predicted",
    )

In [4]:
def summary_relation_FP(dataset, relation, summary_data, not_long=True):
    """
    Given a dataset and a relation, it outputs the sentences the model outputs the relation while the correct one is different (i.e. TP and FP for that relation).
    It provides some summaries (number of wrong relations, predicted relations, number of sentences with long distance between entities).
    Afterwards, it prints the sentences along with the entities and the predicted relations.
    If not_long is True, it only prints the sentences where the distance between entities is NOT long
    """
    data_relation = test_data[dataset["predicted"] == relation]
    print(
        f"Number of sentences where the model predicts relation {relation} : {len(data_relation)}"
    )

    data_relation_wrong = data_relation[data_relation["relation"] != relation]
    print(
        f"Number of sentences where the model outputs {relation} but the true one is a different one: {len(data_relation_wrong)}"
    )

    data_relation_wrong_not_long = data_relation_wrong[
        data_relation_wrong["entity_distance_categorical"] != "long"
    ]
    print(
        f"Of those sentences, {len(data_relation_wrong) - len(data_relation_wrong_not_long)} have long distance between entities"
    )

    wrong_relations_summary = data_relation_wrong["relation"].value_counts()
    print(
        f"\nSummary of true relations to which {relation} is wrongly assigned:\n{wrong_relations_summary}\n"
    )

    print(f"List of (NOT LONG) sentences with relation {relation} assigned wrongly")
    print_sentence_relation_subj_obj(
        data_relation_wrong_not_long if not_long else data_relation_wrong,
        print_text="relation",
    )

## Relation-specific error analysis.
In this notebook a more detailed breakdown of the most misclassified relations is achieved. In order to do this, we start by focusing on the relations where we saw we had 0 recall.

In [6]:
tacrev_results = pd.read_csv("predictions_tacrev.txt", sep="\t")

In [7]:
summary_data = scorer.score(
    tacrev_results["Gold Label"],
    tacrev_results["Prediction"],
    verbose=True,
    return_data=True,
).rename(
    columns={
        "F1": "Tacred_F1",
        "Precision": "Tacred_precision",
        "Recall": "Tacred_recall",
    }
)
summary_data.rename(
    columns={
        "Relation": "relation",
        "Tacred_precision": "Tacrev_precision",
        "Tacred_recall": "Tacrev_recall",
        "Tacred_F1": "Tacrev_F1",
    },
    inplace=True,
)

Per-relation statistics:
org:alternate_names                  P:  78.20%  R:  67.35%  F1:  72.37%  #: 245
org:city_of_headquarters             P:  68.49%  R:  56.18%  F1:  61.73%  #: 89
org:country_of_headquarters          P:  44.29%  R:  33.70%  F1:  38.27%  #: 92
org:dissolved                        P: 100.00%  R:   0.00%  F1:   0.00%  #: 1
org:founded                          P: 100.00%  R:   0.00%  F1:   0.00%  #: 37
org:founded_by                       P: 100.00%  R:   0.00%  F1:   0.00%  #: 76
org:member_of                        P: 100.00%  R:   0.00%  F1:   0.00%  #: 4
org:members                          P: 100.00%  R:   0.00%  F1:   0.00%  #: 16
org:number_of_employees/members      P: 100.00%  R:   0.00%  F1:   0.00%  #: 14
org:parents                          P:   0.00%  R:   0.00%  F1:   0.00%  #: 57
org:political/religious_affiliation  P:  11.11%  R:  10.00%  F1:  10.53%  #: 10
org:shareholders                     P: 100.00%  R:   0.00%  F1:   0.00%  #: 3
org:stateorprovince_of_headquarters  P:  64.71%  R:  21.57%  F1:  32.35%  #: 51
org:subsidiaries                     P:   0.00%  R:   0.00%  F1:   0.00%  #: 31
org:top_members/employees            P:  47.50%  R:  70.98%  F1:  56.91%  #: 348
org:website                          P:  60.00%  R:  44.44%  F1:  51.06%  #: 27
per:age                              P:  49.58%  R:  58.71%  F1:  53.76%  #: 201
per:alternate_names                  P: 100.00%  R:   0.00%  F1:   0.00%  #: 1
per:cause_of_death                   P:  45.83%  R:  23.40%  F1:  30.99%  #: 47
per:charges                          P:  66.67%  R:   7.55%  F1:  13.56%  #: 106
per:children                         P: 100.00%  R:   0.00%  F1:   0.00%  #: 39
per:cities_of_residence              P:  29.37%  R:  28.46%  F1:  28.91%  #: 130
per:city_of_birth                    P:   0.00%  R:   0.00%  F1:   0.00%  #: 6
per:city_of_death                    P: 100.00%  R:   0.00%  F1:   0.00%  #: 16
per:countries_of_residence           P:  40.52%  R:  47.69%  F1:  43.82%  #: 130
per:country_of_death                 P: 100.00%  R:   0.00%  F1:   0.00%  #: 10
per:date_of_birth                    P: 100.00%  R:   0.00%  F1:   0.00%  #: 7
per:date_of_death                    P: 100.00%  R:   0.00%  F1:   0.00%  #: 42
per:employee_of                      P:  27.92%  R:  82.54%  F1:  41.73%  #: 252
per:origin                           P:  43.54%  R:  57.66%  F1:  49.61%  #: 111
per:other_family                     P: 100.00%  R:   0.00%  F1:   0.00%  #: 37
per:parents                          P:   0.00%  R:   0.00%  F1:   0.00%  #: 86
per:religion                         P:  36.36%  R:   9.30%  F1:  14.81%  #: 43
per:schools_attended                 P:  36.36%  R:  25.81%  F1:  30.19%  #: 31
per:siblings                         P: 100.00%  R:   0.00%  F1:   0.00%  #: 59
per:spouse                           P:  16.67%  R:   3.03%  F1:   5.13%  #: 66
per:stateorprovince_of_birth         P: 100.00%  R:   0.00%  F1:   0.00%  #: 7
per:stateorprovince_of_death         P: 100.00%  R:   0.00%  F1:   0.00%  #: 13
per:stateorprovinces_of_residence    P:  41.82%  R:  31.51%  F1:  35.94%  #: 73
per:title                            P:  57.72%  R:  94.70%  F1:  71.73%  #: 509

In [13]:
# Load data from JSON file
with open("../../../data/tacred/json/train.json", "r") as file:
    data_train = json.load(file)

# Convert JSON data to DataFrame
training_data = pd.json_normalize(data_train)

# Count occurrences of each relation in the training set
relation_counts = training_data["relation"].value_counts()

# Reset index and rename columns
train_counts_df = relation_counts.reset_index()
train_counts_df.rename(
    columns={"index": "relation", "relation": "train_counts"}, inplace=True
)

# Assuming summary_data has a column named 'relation'
summary_data = pd.merge(summary_data, train_counts_df, on="relation")

In [14]:
summary_data["train_counts"].describe()

count      40.000000
mean      303.350000
std       472.763103
min         6.000000
25%        75.500000
50%       143.500000
75%       305.750000
max      2287.000000
Name: train_counts, dtype: float64

Consider on which relations the lower precision and recall levels are achieved (excluding those with recall 0):

In [15]:
summary_data[summary_data["Tacrev_recall"] != 0].sort_values(
    "Tacrev_precision"
).head()  # Most of these relations are below the mean but far from being the smallest (see distr above)

,relation,Tacrev_precision,Tacrev_recall,Tacrev_F1,test_counts,train_counts
10,org:political/religious_affiliation,0.111111,0.100000,0.105263,10,95
35,per:spouse,0.166667,0.030303,0.051282,66,240
28,per:employee_of,0.279195,0.825397,0.417252,252,1441
21,per:cities_of_residence,0.293651,0.284615,0.289062,130,351
32,per:religion,0.363636,0.093023,0.148148,43,51

In [16]:
# These appear to be quite large for what concerns the training counts, so would have to be investigated.
summary_data[summary_data["Tacrev_recall"] != 0].sort_values("Tacrev_recall").head()

,relation,Tacrev_precision,Tacrev_recall,Tacrev_F1,test_counts,train_counts
35,per:spouse,0.166667,0.030303,0.051282,66,240
19,per:charges,0.666667,0.075472,0.135593,106,68
32,per:religion,0.363636,0.093023,0.148148,43,51
10,org:political/religious_affiliation,0.111111,0.100000,0.105263,10,95
12,org:stateorprovince_of_headquarters,0.647059,0.215686,0.323529,51,221

Note that all the relationships above fall in the category of relations which have a reverse relation or some similar relations (both in terms of logical sense but also as described in the guidelines for the annotations, where the annotators are explicitly told to not confuse certain instances).

For this reason we decided to investigate these groups of relationships further as they also included those relations for which the model has recall 0. When looking into the sentences predicted wrongly directly, we exclude the sentences which fall in the category of having long distance between the subject and object entities.

In [17]:
with open("../../../data/tacrev/json/test.json", "r") as file:
    test_data = json.load(file)
test_data = pd.json_normalize(test_data)

In [18]:
test_data["predicted"] = tacrev_results["Prediction"]
test_data["entity_distance"] = [
    (test_data["subj_start"][i] - test_data["obj_end"][i])
    if test_data["subj_start"][i] > test_data["obj_end"][i]
    else (test_data["obj_start"][i] - test_data["subj_end"][i])
    for i in range(len(test_data))
]
q1_ed = test_data["entity_distance"].quantile(0.3333)
q2_ed = test_data["entity_distance"].quantile(0.6666)
test_data["entity_distance_categorical"] = [
    "short"
    if test_data["entity_distance"][i] < q1_ed
    else ["long" if test_data["entity_distance"][i] > q2_ed else "medium"][0]
    for i in range(len(test_data))
]

- - - 
## ORG: Relations
### Focus on the family of relations relative to membership and relations with other companies/organisations
From these family we consider these types of relations, as they are mentioned as (be careful it is different from) in the slot annotation guidelines.
- `org:member_of` and `org:member` (opposite relations)
- `org:parents` and `org:subsidiaries` (opposite relations)
- `org:shareholders`

First of all extract statistics for these relationships:

In [19]:
membership_relations = [
    "org:member_of",
    "org:members",
    "org:parents",
    "org:subsidiaries",
    "org:shareholders",
]
filtered_summary_data = summary_data[
    summary_data["relation"].isin(membership_relations)
].sort_values("Tacrev_precision", ascending=False)
filtered_summary_data

,relation,Tacrev_precision,Tacrev_recall,Tacrev_F1,test_counts,train_counts
6,org:member_of,1.0,0.0,0.0,4,113
7,org:members,1.0,0.0,0.0,16,155
11,org:shareholders,1.0,0.0,0.0,3,70
9,org:parents,0.0,0.0,0.0,57,268
13,org:subsidiaries,0.0,0.0,0.0,31,278

Let us start by investigate `org:shareholders` and  `org:member_of` and `org:member`  which are never predicted by the model

In [20]:
summary_relation_FN(test_data, "org:shareholders", summary_data)

Number of sentences with relation org:shareholders : 3
Number of sentences with wrong relation org:shareholders : 3
Of those sentences, 0 have long distance between entities

Summary of relations assigned instead of org:shareholders:
no_relation                  2
org:top_members/employees    1
Name: predicted, dtype: int64

List of (NOT LONG) sentences with relation org:shareholders wrongly predicted
predicted: org:top_members/employees (id: 098f6cd9013bf31021bb)
Subject: ['Sycamore', 'Valley', 'Ranch', 'Co.']
Object: ['Jackson']
Sycamore Valley Ranch Co. is a joint venture between Jackson and an affiliate of Colony Capital LLC , according to person with knowledge of the transaction who was not authorized to speak on the record and requested anonymity .

predicted: no_relation (id: 098f6cd90161b39172fd)
Subject: ['Alico']
Object: ['AIG']
AIG first signaled its intent to offer the government stakes in AIA and Alico on March 2 , the same day that the company posted a staggering $ 62 billion loss for the final quarter of 2008 and nearly $ 100 billion for the year .

predicted: no_relation (id: 098f6f706047d969b47b)
Subject: ['ALICO']
Object: ['Federal', 'Reserve', 'Bank', 'of', 'New', 'York']
The first $ 9 billion in proceeds from the sale will go toward redeeming preferred shares in ALICO held by the Federal Reserve Bank of New York , with the remainder to be used to reduce the New York Fed 's lending commitment to AIG .

In [21]:
summary_relation_FP(test_data, "org:shareholders", summary_data)

Number of sentences where the model predicts relation org:shareholders : 0
Number of sentences where the model outputs org:shareholders but the true one is a different one: 0
Of those sentences, 0 have long distance between entities

Summary of true relations to which org:shareholders is wrongly assigned:
Series([], Name: relation, dtype: int64)

List of (NOT LONG) sentences with relation org:shareholders assigned wrongly

There are only 3 sentences, none of which has a large ditance between the subject and the object. The model predicts twice "no_relation" and once "org:top_members/employees" which could be seen as similar to the right prediction.

In [22]:
summary_relation_FN(test_data, "org:member_of", summary_data)

Number of sentences with relation org:member_of : 4
Number of sentences with wrong relation org:member_of : 4
Of those sentences, 2 have long distance between entities

Summary of relations assigned instead of org:member_of:
no_relation    4
Name: predicted, dtype: int64

List of (NOT LONG) sentences with relation org:member_of wrongly predicted
predicted: no_relation (id: 098f6784e78abd5c3e0c)
Subject: ['ALICO']
Object: ['AIG']
ALICO , a member company of AIG is looking for one J2EE developer to help with a significant re-engineering project .

predicted: no_relation (id: 098f6e00a8db2ff2cd29)
Subject: ['UASR']
Object: ['Muslim', 'Brotherhood', "'s", 'Palestine', 'Committee']
During the trial , FBI agent Lara Burns testified that UASR was part of the Muslim Brotherhood 's Palestine Committee in America < http://www.investigativeproject.org/article/361 > .

In [23]:
summary_relation_FP(test_data, "org:member_of", summary_data)

Number of sentences where the model predicts relation org:member_of : 0
Number of sentences where the model outputs org:member_of but the true one is a different one: 0
Of those sentences, 0 have long distance between entities

Summary of true relations to which org:member_of is wrongly assigned:
Series([], Name: relation, dtype: int64)

List of (NOT LONG) sentences with relation org:member_of assigned wrongly

In this case there are 4 sentences, 2 of which have a long distance between the subject and the object, in these cases the model predicts no_relation and org:parents. 
On the other side the model wrongly assign org:member_of relation to a case where the right prediction is org:parents. It looks like the model is inverting the labels in this case.

In [24]:
summary_relation_FN(test_data, "org:members", summary_data)

Number of sentences with relation org:members : 16
Number of sentences with wrong relation org:members : 16
Of those sentences, 9 have long distance between entities

Summary of relations assigned instead of org:members:
no_relation                    14
org:country_of_headquarters     1
org:alternate_names             1
Name: predicted, dtype: int64

List of (NOT LONG) sentences with relation org:members wrongly predicted
predicted: no_relation (id: 098f6e00a8a07ffb432f)
Subject: ['Organization', 'of', 'Asia', '-', 'Pacific', 'News', 'Agencies']
Object: ['Azerbaijani', 'wire', 'service']
Trend , an Azerbaijani wire service , on Thursday became a full member of the Organization of Asia - Pacific News Agencies -LRB- OANA -RRB- .

predicted: org:country_of_headquarters (id: 098f6e00a8c213b31b91)
Subject: ['Pacific', 'Asia', 'Travel', 'Association']
Object: ['Taiwan']
The fair was organized by the Pacific Asia Travel Association , of which Taiwan is a senior member .

predicted: org:alternate_names (id: 098f6e00a84925a504b7)
Subject: ['Central', 'American', 'Parliament']
Object: ['Panama']
Panama has submitted a letter of intention to quit the Central American Parliament -LRB- PARLACEN -RRB- , the foreign ministry said Wednesday .

predicted: no_relation (id: 098f6e00a8130bae6d80)
Subject: ['PATA']
Object: ['SAR', "'s", 'Tourist', 'Office']
MACAO , Sept 14 -LRB- Xinhua -RRB- The SAR 's Tourist Office is a member of PATA .

predicted: no_relation (id: 098f6e00a8875c6dfbbd)
Subject: ['OANA']
Object: ['AAP']
OANA members include , to name just a few , Australia 's AAP , China 's Xinhua , India 's PTI , Indonesia 's ANTARA , Iran 's IRNA , Japan 's Kyodo and Jiji Press , Pakistan 's PPI and APP , Kazakhstan 's Kazinform , Kuwait 's KUNA , Mongolia 's MONTSAME , the Philippines ' PNA , Russia 's Itar-Tass and RIA , Saudi Arabia 's SPA , the Republic of Korea 's Yonhap , and Turkey 's Anadolu .

predicted: no_relation (id: 098f6e00a8fdb802d661)
Subject: ['Central', 'American', 'Parliament']
Object: ['Panama']
Panama withdraws from Central American Parliament Its resolutions are not binding .

predicted: no_relation (id: 098f6e00a8af57214507)
Subject: ['OANA']
Object: ['Malaysian', 'National', 'News', 'Agency']
New media , including online news portals , blogs and social networking sites , were increasing their reach to the masses while traditional media particularly newspapers saw a decline in overall readership , said a paper presented to the assembly by the Malaysian National News Agency -LRB- BERNAMA -RRB- , an OANA member .

In [69]:
summary_relation_FP(test_data, "org:members", summary_data)

Number of sentences where the model predicts relation org:members : 17
Number of sentences where the model outputs org:members but the true one is a different one: 17
Of those sentences, 1 have long distance between entities

Summary of true relations to which org:members is wrongly assigned:
relation
no_relation            16
org:alternate_names     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:members assigned wrongly
relation: no_relation (id: 098f665fb9ded45248e8)
Subject: ['Koch', 'Foods']
Object: ['Customs', 'Enforcement']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant in southwest Ohio and at Koch Foods Inc. 's Chicago-area headquarters , said Brian Moskowitz , an agent in charge of ICE enforcement for Ohio and Michigan .

relation: no_relation (id: 098f665fb9df7cd35240)
Subject: ['Koch', 'Foods']
Object: ['Customs', 'Enforcement']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant and at Koch Foods Inc. 's Chicago area headquarters , said Brian Moskowitz , a special agent for ICE enforcement .

relation: no_relation (id: 098f665fb9f556aa368b)
Subject: ['Urban', 'League']
Object: ['NAACP']
Last week , the NAACP , the Urban League , and other organizations called for Congress to repeal the ban .

relation: no_relation (id: 098f665fb921b2f1843e)
Subject: ['National', 'Urban', 'League']
Object: ['YWCA']
The organization is a coalition of advocacy groups , including the National Urban League , 100 Black Men in America and the YWCA .

relation: no_relation (id: 098f665fb9ac8f71b69e)
Subject: ['China', 'Charity', 'Federation']
Object: ['Red', 'Cross', 'Society']
This was in addition to 462 houses funded by the Chinese Red Cross Society , the China Charity Federation , the Macao Red Cross and other non-governmental organizations in China .

relation: no_relation (id: 098f665fb981df9f6a8d)
Subject: ['China', 'Charity', 'Federation']
Object: ['MCA']
The MCA had received donations of 361 million yuan and the China Charity Federation had received about 603 million yuan .

relation: org:alternate_names (id: 098f6a9e369970430c0a)
Subject: ['Alico']
Object: ['American', 'Life', 'Insurance', 'Co']
The two companies were preparing to announce that AIG had agreed to sell American Life Insurance Co , better known as Alico , for 68 billion dollars in cash and 87 billion in MetLife equity , the report said .

relation: no_relation (id: 098f665fb9b20e1b7f91)
Subject: ['China', 'Charity', 'Federation']
Object: ['RCSC']
Jiang Yiman , vice standing president of the RCSC and Liu Guolin , general secretary of the China Charity Federation , both present at the press conference , vowed timely delivery of donations to needy people .

relation: no_relation (id: 098f665fb9fee28ad185)
Subject: ['National', 'Urban', 'League']
Object: ['NAACP']
The Black Leadership Forum is an umbrella group of 36 civil rights organizations , including the NAACP and the National Urban League .

relation: no_relation (id: 098f665fb9a2a9e9f6f2)
Subject: ['Koch', 'Foods']
Object: ['Customs', 'Enforcement']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant and at Koch Foods Inc. 's Chicago area headquarters , said Brian Moskowitz , a special agent in charge of ICE enforcement for Ohio and Michigan .

relation: no_relation (id: 098f665fb9097b81415f)
Subject: ['Professional', 'Ski', 'Instructors', 'of', 'America']
Object: ['Times']
Fiore remained vigilant in pushing to maintain high standards for the certification of ski instructors , John Armstrong , president of the Professional Ski Instructors of America and director of corporate training at Mammoth Mountain , told the Times in 2004 .

relation: no_relation (id: 098f665fb9d4dc14589b)
Subject: ['National', 'Urban', 'League']
Object: ['NAACP']
This week , several civil rights groups , including the NAACP and the National Urban League , criticized Race to the Top and elements of the administration 's blueprint that favor reform competition .

relation: no_relation (id: 098f665fb9b9a7e20bcf)
Subject: ['Countrywide']
Object: ['Bank', 'of', 'America']
In August , when US mortgage-related woes started to roil financial markets in the United States and other industrialized countries , Bank of America bought a 16 percent stake in Countrywide in a deal worth two billion dollars .

relation: no_relation (id: 098f6f706072e61d0d80)
Subject: ['TPIPL']
Object: ['Stock', 'Exchange', 'of', 'Thailand']
The Stock Exchange of Thailand ordered temporary suspension of TPIPL trading after the verdict .

relation: no_relation (id: 098f665fb916761a6585)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['AFP']
The average maximum retail price for petrol has jumped 4.1 percent to 8,220 yuan a tonne , according to AFP calculations based on figures provided by the National Development and Reform Commission .

relation: no_relation (id: 098f665fb92befdba0c2)
Subject: ['China', 'Charity', 'Federation']
Object: ['Red', 'Cross', 'Society', 'of', 'China']
In a statement , the ministry said it had received 2.417 billion yuan and the Qinghai provincial government received over 2 billion yuan in donations , while the Red Cross Society of China and the China Charity Federation had each raised about 2 billion yuan .

The model mainly assign no_relation. In some cases it assigns org:alternate_names when it should assign org:members and viceversa: a reason for these missclassifications could be that the model is not taking into account the context.

In [76]:
summary_relation_FN(test_data, "org:parents", summary_data)

Number of sentences with relation org:parents : 57
Number of sentences with wrong relation org:parents : 53
Of those sentences, 7 have long distance between entities

Summary of relations assigned instead of org:parents:
predicted
no_relation                    46
org:alternate_names             2
org:top_members/employees       2
org:member_of                   1
org:subsidiaries                1
org:country_of_headquarters     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:parents wrongly predicted
predicted: no_relation (id: 098f6f7060adc06158f3)
Subject: ['ALICO']
Object: ['MetLife', 'Inc']
It sold ALICO to MetLife Inc for $ 162 billion .

predicted: no_relation (id: 098f6f70609f424b7b16)
Subject: ['Countrywide', 'Financial', 'Corp.']
Object: ['Bank', 'of', 'America', 'Corp.']
Bank of America Corp. is taking a similar approach with newly acquired Countrywide Financial Corp. as part of an $ 8.4 billion , 12-state legal settlement reached this month .

predicted: org:alternate_names (id: 098f6f7060ba34725b28)
Subject: ['ALICO']
Object: ['MetLife', 'Inc']
AIA says IPO raised 205 billion US dollars AIG said Monday it had also raised 162 billion dollars by selling unit American Life Insurance Company -LRB- ALICO -RRB- to MetLife Inc .

predicted: no_relation (id: 098f6f70606cafa45645)
Subject: ['ALICO']
Object: ['AIG']
In late June , AIG said it would move ALICO and American International Assurance Co. into special purpose vehicles ahead of planned initial public offerings of the two divisions .

predicted: no_relation (id: 098f6f7060f058974563)
Subject: ['ALICO']
Object: ['MetLife']
The initial offering of AIA raised $ 178 billion for AIG , while the sale of ALICO to MetLife reaped about $ 155 billion .

predicted: no_relation (id: 098f6f706044bfec4de8)
Subject: ['Countrywide', 'Financial', 'Corp.']
Object: ['Bank', 'of', 'America', 'Corp.']
Dozens of lightly regulated subprime lenders , including New Century Financial Corp. , have failed and troubled Countrywide Financial Corp. was acquired by Bank of America Corp. .

predicted: no_relation (id: 098f6784e7b54195a275)
Subject: ['ALICO']
Object: ['AIG']
MetLife says it acquires AIG unit ALICO for 15.5 billion dollars

predicted: org:member_of (id: 098f6f7060de60b597c7)
Subject: ['Koch', 'Foods']
Object: ['Koch', 'Foods', 'Inc.']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant in southwest Ohio and at Koch Foods Inc. 's Chicago-area headquarters , said Brian Moskowitz , an agent in charge of ICE enforcement for Ohio and Michigan .

predicted: no_relation (id: 098f6f7060e84075d409)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Cabinet']
China 's planning agency , the Cabinet 's National Development and Reform Commission , was working on a plan for more spending on schools , health and other social programs , according to the Economic Observer , a leading Chinese business newspaper .

predicted: no_relation (id: 098f6f706051ca2246a3)
Subject: ['Countrywide', 'Financial']
Object: ['BofA']
Shares of Bank of America Corp. fell 4.8 percent , a day after reports that a group of institutional bond holders and the Federal Reserve Bank of New York are looking to force the bank to repurchase billion of dollars in mortgage bonds issued by Countrywide Financial , which BofA bought in 2008 .

predicted: no_relation (id: 098f6f7060e83ebbe308)
Subject: ['ALICO']
Object: ['MetLife']
MetLife says it acquires AIG unit ALICO for 15.5 billion dollars

predicted: no_relation (id: 098f6f70607381dfb4c8)
Subject: ['ALICO']
Object: ['MetLife']
The initial offering of AIA raised $ 17.8 billion for AIG , while the sale of ALICO to MetLife reaped about $ 15.5 billion .

predicted: no_relation (id: 098f665fb944662227e0)
Subject: ['Third', 'Guard', 'Division']
Object: ['People', "'s", 'Liberation', 'Army']
The People 's Liberation Army 's Third Guard Division gave journalists a tour of their living and dining quarters and a display of marksmanship and artillery firepower at their base , about an hour 's drive north of Beijing .

predicted: no_relation (id: 098f6784e79b17305ae1)
Subject: ['Sycamore', 'Valley', 'Ranch', 'Co.']
Object: ['Colony', 'Capital', 'LLC']
Sycamore Valley Ranch Co. is a joint venture between Jackson and an affiliate of Colony Capital LLC , according to person with knowledge of the transaction who was not authorized to speak on the record and requested anonymity .

predicted: no_relation (id: 098f6f70600000f69dd2)
Subject: ['ALICO']
Object: ['AIG']
AIG SELLS ALICO TO METLIFE

predicted: no_relation (id: 098f6f7060e0246fb137)
Subject: ['Alico']
Object: ['AIG']
Under the agreement , AIG will split off AIA and Alico into separate company-owned entities called `` special purpose vehicles , '' or SPVs .

predicted: no_relation (id: 098f6f70600ee130beb3)
Subject: ['ALICO']
Object: ['AIG']
AIG MOVES CLOSER TO SALE OF ALICO UNIT

predicted: no_relation (id: 098f6f7060dc27aea9bf)
Subject: ['Third', 'Guard', 'Division']
Object: ['People', "'s", 'Liberation', 'Army']
The People 's Liberation Army 's Third Guard Division gave journalists a tour of their living and dining quarters and a display of marksmanship and artillery fire power at their base about an hour 's drive north of Beijing .

predicted: no_relation (id: 098f6f7060ed01c55889)
Subject: ['Third', 'Guard', 'Division']
Object: ['The', 'People', "'s", 'Liberation', 'Army']
The People 's Liberation Army 's Third Guard Division gave journalists a tour of their living and dining quarters and a display of marksmanship and artillery fire power at their base about an hour 's drive north of Beijing .

predicted: no_relation (id: 098f6cd901975f8a1151)
Subject: ['Countrywide', 'Financial']
Object: ['Bank', 'of', 'America']
He figured that he would sell his home before the interest rate on the loan , taken out from Countrywide Financial , now owned by Bank of America , reset at a higher level .

predicted: no_relation (id: 098f6f7060fb18e5fbb4)
Subject: ['ALICO']
Object: ['MetLife']
But the purchase of ALICO by MetLife also carries uncertainties .

predicted: no_relation (id: 098f6f70608f74a0cc69)
Subject: ['TPI']
Object: ['Information', 'Services', 'Group']
Information Services Group purchased TPI in October .

predicted: no_relation (id: 098f6f706026a5989562)
Subject: ['ALICO']
Object: ['Federal', 'Reserve', 'Bank']
AIG said it had transferred ownership to the Federal Reserve Bank of parts of two subsidiaries , ALICO which is active in life assurance in the United States and AIA which provides life assurance abroad .

predicted: org:top_members/employees (id: 098f6cd9017cf58fc1c3)
Subject: ['Countrywide', 'Financial']
Object: ['Bank', 'of', 'America', 'Corp']
Dodd 's popularity waned after Portfolio magazine reported in 2008 that he and Sen Kent Conrad , D-ND , received discounts on home loans from Countrywide Financial , now part of Bank of America Corp .

predicted: no_relation (id: 098f6f7060f12e6cc0e1)
Subject: ['Australian', 'Defence', 'Force']
Object: ['Australian', 'Government']
The four Australian Government agencies involved in aviation policy : Airservices Australia , the Australian Defence Force , the Civil Aviation Safety Authority and the Department of Transport and Regional Services ; are seeking comment on the proposed wider application of ADS-B and GNSS technologies .

predicted: no_relation (id: 098f6f70601666f31b5b)
Subject: ['Alico']
Object: ['American', 'International', 'Group']
AIG-METLIFE -LRB- Undated -RRB- -- The American International Group agreed Sunday to sell a major insurance unit , Alico , to MetLife for about $ 155 billion , according to people briefed on the matter .

predicted: no_relation (id: 098f6f7060ede9e6aa21)
Subject: ['ALICO']
Object: ['MetLife', 'Inc.']
It sold ALICO to MetLife Inc. for $ 16.2 billion .

predicted: org:top_members/employees (id: 098f6cd9015b5f85c142)
Subject: ['Countrywide', 'Financial']
Object: ['BofA']
Financials were the weakest as investors continue to question what the impact will be over reports that the New York Federal Reserve will join institutional bond holders in an effort to force Bank of America Corp to repurchase billions of dollars in mortgage bonds issued by Countrywide Financial , which BofA purchased in 2008 .

predicted: no_relation (id: 098f665fb928f7437e01)
Subject: ['ALICO']
Object: ['American', 'International', 'Group']
US life insurance giant MetLife said on Monday it will acquire American International Group unit American Life Insurance company -LRB- ALICO -RRB- in a deal worth 15.5 billion dollars .

predicted: org:subsidiaries (id: 098f6f7060a3c10d325c)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Cabinet']
The fuel released on Wednesday and Thursday brings the amount of oil distributed from the national reserve to disaster areas to 169,365 barrels , the Cabinet 's National Development and Reform Commission said .

predicted: no_relation (id: 098f665fb9c380684adf)
Subject: ['Third', 'Guard', 'Division']
Object: ['army']
Senior Colonel Leng Jiesong , head of the army 's Third Guard Division , told journalists that the tour was part of a policy of increased openness .

predicted: org:country_of_headquarters (id: 098f6f70604f3ac0f542)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['China']
Xie Zhenhua , vice minister in charge of the National Development and Reform Commission -LRB- NDRC -RRB- , China 's top economic planner , made the remarks at a press conference .

predicted: no_relation (id: 098f6f706082ebaf2f99)
Subject: ['Texas', 'Petro', 'Index']
Object: ['Texas', 'Alliance', 'of', 'Energy', 'Producers']
This news comes from Karr Ingham , an economist who created the Texas Petro Index -LRB- TPI -RRB- , which is a service of the Texas Alliance of Energy Producers .

predicted: no_relation (id: 098f6f7060c19615328c)
Subject: ['Countrywide', 'Bank.']
Object: ['Countrywide', 'Financial', 'Corporation', ',', 'Inc.']
Countrywide Bank. , a subsidiary of Countrywide Financial Corporation , Inc. -LRB- NYSE : CFC -RRB- , is among the nation & # 8217 ; s fastest-growing and ranks among the 20 largest national banks .

predicted: no_relation (id: 098f6f70604226eecf90)
Subject: ['ALICO']
Object: ['AIG']
AIG sold ALICO to MetLife in March .

predicted: no_relation (id: 098f6c74c544c36649a3)
Subject: ['ALICO']
Object: ['AIG']
In the sale of unit American Life Insurance Company -LRB- ALICO -RRB- to MetLife , Inc , AIG raised about 162 billion dollars , including about 72 billion dollars in cash .

predicted: no_relation (id: 098f6c74c58f11662010)
Subject: ['ALICO']
Object: ['AIG']
ALERT ¥ MetLife says it acquires AIG unit ALICO for 155 billion dollars

predicted: no_relation (id: 098f6f7060254b53b8d8)
Subject: ['Countrywide']
Object: ['N.C.-based', 'Bank', 'of', 'America']
Countrywide is now part of Charlotte , N.C.-based Bank of America .

predicted: no_relation (id: 098f6f70600511413fdf)
Subject: ['ALICO']
Object: ['METLIFE']
NEW NATURAL HISTORY CABLE CHANNEL COMING AIG SELLS ALICO TO METLIFE OSCARS TOUGH TO VIEW IN NEW YORK DISPUTE OVER AIR-PLAY ROYALTIES BUSINESS NEWS AT A GLANCE FOR PUBLICATION ON MONDAY , MARCH 8 .

predicted: no_relation (id: 098f6f7060dcb3a5b42e)
Subject: ['ALICO']
Object: ['AIG']
LONDON 2010-08-06 10:54:24 UTC AIG sold ALICO to MetLife in March .

predicted: no_relation (id: 098f6c74c51c4dd67510)
Subject: ['American', 'Life', 'Insurance', ',', 'known', 'as', 'ALICO']
Object: ['AIG']
At the time , AIG said it would place American Life Insurance , known as ALICO , and American International Assurance , known as AIA Group , into SPVs .

predicted: no_relation (id: 098f6f7060ab45a450f2)
Subject: ['ALICO']
Object: ['MetLife']
ALERT ¥ MetLife says it acquires AIG unit ALICO for 155 billion dollars

predicted: no_relation (id: 098f6f7060d93a4ce2ad)
Subject: ['ALICO']
Object: ['AIG']
AIA and ALICO would remain wholly owned subsidiaries of AIG , and the insurance giant would continue to operate them .

predicted: no_relation (id: 098f6c74c574c32dcb8e)
Subject: ['Third', 'Guard', 'Division']
Object: ['army']
Senior Colonel Leng Jiesong , head of the army 's Third Guard Division , told journalists the tour was part of a policy of increased openness .

predicted: no_relation (id: 098f6c74c5e9839634b9)
Subject: ['Drawings', 'Institute']
Object: ['Menil', 'Collection']
091407 - Bernice Berend Rose , a director of drawings and special exhibitions at the PaceWildenstein Gallery in New York and earlier a longtime curator at the Museum of Modern Art , has been named chief curator of the Menil Collection 's new Drawings Institute in Houston .

predicted: no_relation (id: 098f6c74c55313d8127b)
Subject: ['ALICO']
Object: ['American', 'International', 'Group']
US life insurance giant MetLife said on Monday it will acquire American International Group unit American Life Insurance company -LRB- ALICO -RRB- in a deal worth 155 billion dollars .

In [77]:
summary_relation_FP(test_data, "org:parents", summary_data)

Number of sentences where the model predicts relation org:parents : 44
Number of sentences where the model outputs org:parents but the true one is a different one: 40
Of those sentences, 7 have long distance between entities

Summary of true relations to which org:parents is wrongly assigned:
relation
no_relation                  32
org:alternate_names           3
org:member_of                 2
org:subsidiaries              2
org:top_members/employees     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:parents assigned wrongly
relation: no_relation (id: 098f665fb951f23140f6)
Subject: ['National', 'Urban', 'League']
Object: ['Census', 'Advisory', 'Committee']
`` In 2000 , we had an undercount in communities of color , and an overcount in white communities , '' said Marc Morial , president of the National Urban League and chairman of the Census Advisory Committee .

relation: no_relation (id: 098f665fb9e7c193b5dc)
Subject: ['Loose', 'Change']
Object: ['Forum']
Loose Change has been remarkably productive , and the Forum is riddled with psyops working double time to both misinform and silence their efforts .

relation: no_relation (id: 098f665fb9519aeaeb31)
Subject: ['Corporate', 'Library']
Object: ['Bank', 'of', 'America']
Paul Hodgson , research associate at the Corporate Library , a corporate governance research firm , criticized Bank of America for agreeing to the terms of Sambol 's exit deal .

relation: no_relation (id: 098f665fb903c294476b)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Chinese', 'Society', 'of', 'Biotechnology']
That is mainly fueled by the booming food and catering industries , said the report co-compiled by the National Development and Reform Commission and the Chinese Society of Biotechnology .

relation: org:alternate_names (id: 098f6a9e36bc4d74500e)
Subject: ['ALICO']
Object: ['American', 'Life', 'Insurance', 'Co']
The boards of both companies met Sunday and approved the sale of the AIG unit , the American Life Insurance Co , known as ALICO , the people briefed on the matter said .

relation: no_relation (id: 098f6e00a8ea2f710195)
Subject: ['American', 'Association', 'of', 'University', 'Women']
Object: ['Willingboro', 'Chapter']
The American Association of University Women , Willingboro Chapter , sponsors the presentation .

relation: no_relation (id: 098f665fb972b05a3f61)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Actions', 'for', 'Addressing', 'Climate', 'Change']
Last month , the National Development and Reform Commission issued the Progress Report 2009 of China 's Policies and Actions for Addressing Climate Change , warning of severe weather around the country .

relation: no_relation (id: 098f665fb981b4835186)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['top', 'economic', 'planning', 'agency']
Chen Bin , a senior official with the National Development and Reform Commission , the country 's top economic planning agency , said China was forecast to produce a record 12 million units for the whole of 2009 .

relation: org:alternate_names (id: 098f665fb99ce5fe7d4c)
Subject: ['ALICO']
Object: ['American', 'Life', 'Insurance', 'Co.']
The boards of both companies met Sunday and approved the sale of the AIG unit , the American Life Insurance Co. , known as ALICO , the people briefed on the matter said .

relation: no_relation (id: 098f665fb9d70b21b388)
Subject: ['National', 'Taiwan', 'Symphony', 'Orchestra']
Object: ['National', 'Experimental', 'Chorus']
The opening ceremony will open with a song performed by the National Taiwan Symphony Orchestra and the National Experimental Chorus , Tseng said .

relation: no_relation (id: 098f665fb929bc263dfd)
Subject: ['ALICO']
Object: ['Wall', 'Street', 'Journal']
News of the potential resolution of the ALICO tax issue was first reported by The Wall Street Journal online .

relation: no_relation (id: 098f665fb92ac8990ef6)
Subject: ['National', 'Restaurant', 'Association']
Object: ['New', 'England', 'Apple', 'Council']
The pleas came from groups as diverse as the National Restaurant Association , the National Council of La Raza , the New England Apple Council and the business software company Oracle .

relation: no_relation (id: 098f665fb921b9163544)
Subject: ['Semen', 'Gresik']
Object: ['United', 'Tractors']
JAKARTA : Indonesian shares hit a new high , led by cement maker Semen Gresik and heavy equipment company United Tractors .

relation: org:member_of (id: 098f6e00a8db2ff2cd29)
Subject: ['UASR']
Object: ['Muslim', 'Brotherhood', "'s", 'Palestine', 'Committee']
During the trial , FBI agent Lara Burns testified that UASR was part of the Muslim Brotherhood 's Palestine Committee in America < http://www.investigativeproject.org/article/361 > .

relation: no_relation (id: 098f665fb9d0decd47bf)
Subject: ['Countrywide']
Object: ['Citigroup']
If it was an economic Pearl Harbor , the enemies were Fannie Mae , Freddie Mac , A.I.G. , Countrywide , Bank of America , Merrill Lynch , Citigroup , Bear Stearns , and all the other banks , brokerages , speculators , insurance companies , hedge funds and leverage buyout specialists that had launched the sneak attack on the American economy .

relation: no_relation (id: 098f665fb9f0bb0d85b6)
Subject: ['Semen', 'Gresik']
Object: ['Blue', 'Valley', 'Holdings', 'Pte', 'Ltd']
The Indonesian government holds a 51 percent stake in Semen Gresik while Rajawali Group through Blue Valley Holdings Pte Ltd owns 24.9 percent .

relation: no_relation (id: 098f665fb98fc40d14c2)
Subject: ['China', 'Charity', 'Federation']
Object: ['Macao', 'Red', 'Cross']
This was in addition to 462 houses funded by the Chinese Red Cross Society , the China Charity Federation , the Macao Red Cross and other non-governmental organizations in China .

relation: org:alternate_names (id: 098f6a9e36b91f245721)
Subject: ['Gay', 'Men', "'s", 'Health', 'Crisis']
Object: ['GMHC']
For Gay Men 's Health Crisis , known as GMHC , there were signs of resistance from building owners , said the group 's chief executive , Marjorie Hill .

relation: no_relation (id: 098f665fb9d929de7acf)
Subject: ['Koch', 'Foods']
Object: ['Customs', 'Enforcement']
U.S. Immigration and Customs Enforcement said the raid was the culmination of a two-year investigation of Koch Foods , suspected of knowingly hiring undocumented workers .

relation: no_relation (id: 098f665fb98a6fae847d)
Subject: ['National', 'Urban', 'League']
Object: ['Morgan', 'State', 'University']
During his stop in Missouri , Giuliani faced questions about his absence from a forum sponsored by the National Urban League in July , and his failure to appear at historically black Morgan State University last month .

relation: no_relation (id: 098f665fb9e64a537e79)
Subject: ['Urban', 'League']
Object: ['NAACP']
As a child , Hansberry witnessed her father 's participation in challenging segregation through his work with the NAACP and the Urban League .

relation: no_relation (id: 098f6e00a84fdc7a56af)
Subject: ['Central', 'American', 'Parliament']
Object: ['Zelaya']
Ousted Honduran president proposes to restore democracy , national reconciliation Zelaya also asked to be a member of the Central American Parliament .

relation: no_relation (id: 098f665fb9541324643d)
Subject: ['Poverty', 'and', 'Social', 'Impact', 'Analysis']
Object: ['World', 'Bank']
Poverty and Social Impact Analysis http://www.worldbank.org/psia This World Bank website was conceived as a forum for interaction and a tool for disseminating experience .

relation: no_relation (id: 098f665fb9a6ce601251)
Subject: ['PATA']
Object: ['WTTC']
Participants at the forum included leaders from the UNWTO , the WTTC , the PATA and tourism ministers from a number of countries .

relation: no_relation (id: 098f665fb9b386ab34e2)
Subject: ['PATA']
Object: ['UNWTO']
Participants at the forum included leaders from the UNWTO , the WTTC , the PATA and tourism ministers from a number of countries .

relation: no_relation (id: 098f665fb91db6ee2cc8)
Subject: ['ALICO']
Object: ['AIG']
The closing of the ALICO deal comes just days after AIG completed an initial public offering in Hong Kong for another foreign insurance unit , AIA Group Ltd. .

relation: no_relation (id: 098f665fb93461f3fe89)
Subject: ['ADF']
Object: ['Constitution']
The ADF believes that the Constitution is not open to interpretation , as does the American Center for Law and Justice , founded by the Rev. Pat Robertson .

relation: org:subsidiaries (id: 098f6c74c57407bbda08)
Subject: ['Countrywide', 'Financial']
Object: ['LandSafe', 'Inc']
LandSafe Inc , a wholly owned subsidiary of Countrywide Financial Corporation , was founded in 1994 and offers , through its various subsidiaries , value-added Real-Estate Closing Services .

relation: no_relation (id: 098f665fb9bb14403889)
Subject: ['Menil', 'Collection']
Object: ['Dia', 'Center', 'for', 'the', 'Arts']
Snow was born in Manhattan in 1981 to a family whose cultural contributions included the Menil Collection in Houston and the Dia Center for the Arts in Manhattan and Beacon , N.Y. .

relation: org:top_members/employees (id: 098f6784e7d904d754d8)
Subject: ['Defence', 'Force']
Object: ['Lieutenant', 'General']
Australian Defence Force chief of joint operations Lieutenant General said Mullah Abdul Karim was killed in an operation on August 10 .

relation: no_relation (id: 098f665fb944ee0ae196)
Subject: ['Urban', 'League']
Object: ['Sidney', 'Hillman', 'Medical', 'Center']
During the 1970s , she held positions in Philadelphia with the Urban League and the Sidney Hillman Medical Center before moving to London to work as deputy director of the Local Organizations Divisions of the National Council for Voluntary Organizations .

relation: org:subsidiaries (id: 098f6c74c51d0732d3bd)
Subject: ['Semen', 'Gresik']
Object: ['Semen', 'Padang']
However , the government let the deal expire in December 2001 amid protests from local politicians and workers at a Semen Gresik unit , Semen Padang in West Sumatra .

relation: no_relation (id: 098f665fb90afac60ccb)
Subject: ['American', 'Association', 'of', 'University', 'Women']
Object: ['Harris', 'Interactive']
One 2000 study , by the American Association of University Women , a nonprofit membership group , and the market research firm Harris Interactive , asked a national sample of 2,064 boys and girls in the 8th through 11th grades if they had ever experienced `` unwanted and unwelcome sexual conduct , '' either verbal or physical , from teachers or school employees .

With the relation org:parents in many cases it missclassifies the relations because it is not taking into account the context, this is clear when looking at sentences in which it assigns org:alternate_name. In same cases, it assigns org:memeber_of which is a different relation but still very similar.

In [79]:
summary_relation_FN(test_data, "org:subsidiaries", summary_data)

Number of sentences with relation org:subsidiaries : 31
Number of sentences with wrong relation org:subsidiaries : 27
Of those sentences, 3 have long distance between entities

Summary of relations assigned instead of org:subsidiaries:
predicted
no_relation      24
org:parents       2
org:member_of     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:subsidiaries wrongly predicted
predicted: no_relation (id: 098f6c74c502d16f9b90)
Subject: ['National', 'Energy', 'Administration']
Object: ['New', 'Energy', 'Department']
The country 's installed wind power capacity will reach 20 gigawatts this year , said Shi Lishan , vice director of the National Energy Administration 's New Energy Department , the Xinhua news agency said Wednesday .

predicted: no_relation (id: 098f6c74c50acc616c22)
Subject: ['Urban', 'League']
Object: ['Colman', 'School']
The Urban League , which bought the Colman School , is confronting the community issue directly .

predicted: no_relation (id: 098f6c74c50534b88ae6)
Subject: ['Tribeca', 'Enterprises']
Object: ['Tribeca', 'Film']
A new distribution company , Tribeca Film , founded by the festival 's parent company Tribeca Enterprises , will make a dozen films -- including Whitecross ' directorial debut `` sex & drugs & rock & roll '' -- available on TV via video-on-demand in some 40 million homes .

predicted: no_relation (id: 098f6c74c5eefd33473d)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Industrial', 'Policy', 'Department']
The proportion stood at 38.7 percent , down 0.5 percentage points from the first half , said Xia Nong , deputy head of the Industrial Policy Department of the National Development and Reform Commission -LRB- NDRC -RRB- , at a press conference in Beijing .

predicted: no_relation (id: 098f6e00a82014806b13)
Subject: ['NDRC']
Object: ['International', 'Economic', 'Research', 'Institute']
`` The country currently has no better measures to solve the monopoly problem in some crucial centrally-administrated and state-owned large enterprise and industrials , '' said Zhang Yansheng , the NDRC 's International Economic Research Institute director .

predicted: no_relation (id: 098f6c74c5d195137d0b)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['International', 'Economic', 'Research', 'Institute']
The trade surplus would probably grow more slowly in 2008 , with the final outcome depending on how much China was affected by a possible economic downturn triggered by the credit crisis in the United States , which remains a key buyer of Asian goods and services , said Zhang Yansheng , head of the International Economic Research Institute under the National Development and Reform Commission .

predicted: no_relation (id: 098f665fb9ff389142c6)
Subject: ['Organisation', 'of', 'Asia-Pacific', 'News', 'Agencies']
Object: ['general', 'assembly']
The general assembly of the Organisation of Asia-Pacific News Agencies -LRB- OANA -RRB- is seeking to boost the quality of the 40 news agencies across 33 countries that comprise it , said incoming OANA head and chief of Indonesia 's state-run Antara news agency Ahmad Mukhlis Yusuf .

predicted: no_relation (id: 098f6c74c5248883a246)
Subject: ['Nuclear', 'Decommissioning', 'Authority']
Object: ['Sellafield']
The consortium , Nuclear Management Partners Ltd. , signed a five - year contract to run the nuclear waste facility , with an option to extend it for another 12 years , according to the government 's Nuclear Decommissioning Authority , which owns Sellafield .

predicted: org:member_of (id: 098f6c74c5144a3688f3)
Subject: ['Countrywide', 'Financial']
Object: ['IndyMac']
One of the banks identified is Countrywide Financial , the former parent company of IndyMac .

predicted: no_relation (id: 098f6c74c564797bb836)
Subject: ['Pluribus', 'Capital', 'Management']
Object: ['E5']
E5 is a joint venture of Pluribus Capital Management , a private equity fund , and Guggenheim Partners , a financial services firm .

predicted: no_relation (id: 098f6c74c5d65a4bc6fe)
Subject: ['NDRC']
Object: ['transportation', 'institute']
`` The 150 yuan cost of a one-way ticket is obviously too high for ordinary people , '' said Prof. Li Hong , a researcher with the NDRC 's transportation institute .

predicted: no_relation (id: 098f6c74c5ab325c0ccc)
Subject: ['ADF']
Object: ['Greenwich', 'Village', 'KFC/Taco', 'Bell']
ADF is the owner of a Greenwich Village KFC/Taco Bell that closed by New York health inspectors last week after TV news crews peering in through the windows recorded a nauseating number of rats skittering across the floors and climbing on tables and countertops .

predicted: no_relation (id: 098f6c74c52ca5b5a38a)
Subject: ['National', 'Restaurant', 'Association']
Object: ['Conserve', 'Solutions', 'Center']
Feature : Fantastic feast greets guests at grand restaurant show in Chicago Besides the Green Restaurant Association 's 800 square-foot presence in the South Hall , the National Restaurant Association also has its own sustainability-related Conserve Solutions Center .

predicted: no_relation (id: 098f6c74c53079649f85)
Subject: ['Tribeca', 'Enterprises']
Object: ['Tribeca', 'Film', 'Festival']
Redford said promoting Cooper to festival director was an easy decision after predecessor Geoff Gilmore departed last year for Tribeca Enterprises , which runs Robert De Niro 's Tribeca Film Festival .

predicted: no_relation (id: 098f6c74c56125e82d31)
Subject: ['PATA']
Object: ['Strategic', 'Intelligence', 'Center']
`` There is a lot of volatility in stock markets ... that 's affecting some business confidence , '' John Koldowski , director of PATA 's Strategic Intelligence Center , told reporters in Singapore .

predicted: no_relation (id: 098f6f7060381ae6439f)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Academy', 'of', 'Macroeconomic', 'Research']
`` China has taken three kinds of policies to boost consumption , including improving residents ' income , encouraging and empowering rural residents to spend , boosting large and popular items consumption such as automobiles and apartments , '' said Sun Xuegong , a researcher at the Academy of Macroeconomic Research under the National Development and Reform Commission .

predicted: no_relation (id: 098f6a9e36bd512d6303)
Subject: ['Tribeca', 'Enterprises']
Object: ['Tribeca']
A new distribution company , Tribeca Film , founded by the festival 's parent company Tribeca Enterprises , will make a dozen films -- including Whitecross ' directorial debut `` sex & drugs & rock & roll '' -- available on TV via video-on-demand in some 40 million homes .

predicted: no_relation (id: 098f6c74c51734f50e17)
Subject: ['AFP']
Object: ['Western', 'Regional', 'Bureau']
ADL falsely charges that I have `` a long-standing affiliation with American Free Press -LRB- AFP -RRB- , an anti-Semitic conspiracy-oriented newspaper.Pike is an AFP staff member , having served on its Western Regional Bureau .

predicted: no_relation (id: 098f6c74c54ba0ce1b97)
Subject: ['Countrywide', 'Financial']
Object: ['Countrywide', 'Securities']
The defendants in the Federal Home Loan Bank case were among the biggest sellers of mortgage-backed securities back in the day ; among those named are Deutsche Bank ; Bear Stearns ; Countrywide Securities , a division of Countrywide Financial ; Credit Suisse Securities ; and Merrill Lynch .

predicted: no_relation (id: 098f665fb92ddffc22f8)
Subject: ['National', 'Urban', 'League']
Object: ['The', 'State', 'of', 'Black', 'America']
Lee A Daniels - author , former editor of the National Urban League 's journal The State of Black America .

predicted: org:parents (id: 098f6c74c57407bbda08)
Subject: ['Countrywide', 'Financial']
Object: ['LandSafe', 'Inc']
LandSafe Inc , a wholly owned subsidiary of Countrywide Financial Corporation , was founded in 1994 and offers , through its various subsidiaries , value-added Real-Estate Closing Services .

predicted: no_relation (id: 098f6c74c5d0d0361c68)
Subject: ['PDA']
Object: ['PDA', 'Virginia']
PDA Virginia is leading a national PDA campaign to pass HR 508 or similar legislation to expedite our withdrawal and begin a new diplomatic approach that can improve our safety and restore respect to the US .

predicted: no_relation (id: 098f6c74c523caf2572b)
Subject: ['Menil', 'Collection']
Object: ['Drawings', 'Institute']
09.14.07 - Bernice Berend Rose , a director of drawings and special exhibitions at the PaceWildenstein Gallery in New York and earlier a longtime curator at the Museum of Modern Art , has been named chief curator of the Menil Collection 's new Drawings Institute in Houston .

predicted: org:parents (id: 098f6c74c51d0732d3bd)
Subject: ['Semen', 'Gresik']
Object: ['Semen', 'Padang']
However , the government let the deal expire in December 2001 amid protests from local politicians and workers at a Semen Gresik unit , Semen Padang in West Sumatra .

In [80]:
summary_relation_FP(test_data, "org:subsidiaries", summary_data)

Number of sentences where the model predicts relation org:subsidiaries : 22
Number of sentences where the model outputs org:subsidiaries but the true one is a different one: 18
Of those sentences, 3 have long distance between entities

Summary of true relations to which org:subsidiaries is wrongly assigned:
relation
no_relation            16
org:alternate_names     1
org:parents             1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:subsidiaries assigned wrongly
relation: no_relation (id: 098f665fb98a41514294)
Subject: ['ADF']
Object: ['Bersama', 'Shield']
Bersama Shield has also provided the ADF with the opportunity to develop relationships with important security partners , while reinforcing Australia 's long-term commitment to regional stability .

relation: no_relation (id: 098f665fb96d22986df7)
Subject: ['American', 'Free', 'Press']
Object: ['Lawrence', 'Livermore', 'National', 'Lab']
`` That 's baloney , '' Marion Fulk , a retired staff scientist from Lawrence Livermore National Lab , told American Free Press .

relation: org:alternate_names (id: 098f6a9e367b3030c8ce)
Subject: ['Koch', 'Foods']
Object: ['Koch', 'Foods', 'Inc.']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant and at Koch Foods Inc. 's Chicago area headquarters , said Brian Moskowitz , a special agent for ICE enforcement .

relation: no_relation (id: 098f665fb95cc22ab731)
Subject: ['Pluribus', 'Capital', 'Management']
Object: ['Guggenheim', 'Partners']
Pluribus Capital Management , a private equity firm , and Guggenheim Partners , a financial services firm , formed e5 , and last month e5 bought several trade publications and trade shows from Nielsen Business Media .

relation: no_relation (id: 098f665fb9197da048e9)
Subject: ['PATA']
Object: ['Ministry', 'of', 'Culture']
This year 's Mart , which was organized jointly by PATA and the Ministry of Culture and Tourism of Indonesia , was attended by about 1,500 representatives of buyers , sellers and journalists .

relation: no_relation (id: 098f665fb95ba3e0cb82)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Yomiuri']
China is also expected to accept another agreement on trading credits earned through Japanese-funded emissions-reduction projects at a climate conference slated for Bali next December , the Yomiuri said , citing an unnamed senior official with China 's National Development and Reform Commission .

relation: no_relation (id: 098f665fb966e0162d2b)
Subject: ['Alico']
Object: ['AIA']
Edward Liddy , AIG 's chief executive , said in a statement that the agreement `` represents a major step toward repaying taxpayers and preserving the value of AIA and Alico . ''

relation: no_relation (id: 098f665fb905a2db600b)
Subject: ['UASR']
Object: ['FBI']
During the trial , FBI agent Lara Burns testified that UASR was part of the Muslim Brotherhood 's Palestine Committee in America < http://www.investigativeproject.org/article/361 > .

relation: no_relation (id: 098f665fb99f4a5c11ab)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['economic', 'planning', 'agency']
China 's chief economic planning agency , the National Development and Reform Commission , estimates that 67,000 such companies went bankrupt in the first half of the year due to credit controls and the deteriorating business environment , the state-run Shanghai Securities News reported .

relation: org:parents (id: 098f6f7060a3c10d325c)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['Cabinet']
The fuel released on Wednesday and Thursday brings the amount of oil distributed from the national reserve to disaster areas to 169,365 barrels , the Cabinet 's National Development and Reform Commission said .

relation: no_relation (id: 098f665fb9b4908042ae)
Subject: ['Tribeca', 'Enterprises']
Object: ['William', 'Morris', 'Agency']
It opens a rich window for Chinese youth on western hip-hop culture , '' said Ms. Hong Huang , CEO of China Interactive Media Group , which co-organized the festival with Tribeca Enterprises and William Morris Agency .

relation: no_relation (id: 098f665fb90acac827cf)
Subject: ['NDA']
Object: ['trade', 'union']
Mike Graham , national officer for Prospect , the trade union , said : `` The NDA 's strategy is in tatters .

relation: no_relation (id: 098f665fb9ac8bf60430)
Subject: ['National', 'Restaurant', 'Association']
Object: ['Multicultural', 'Foodservice', 'and', 'Hospitality', 'Alliance']
`` This is not a new issue , '' said Gerald A. Fernandez , the president of the Multicultural Foodservice and Hospitality Alliance and a director of the National Restaurant Association .

relation: no_relation (id: 098f665fb949c9ed346c)
Subject: ['Pluribus', 'Capital', 'Management']
Object: ['Guggenheim', 'Partners']
E5 is a joint venture of Pluribus Capital Management , a private equity fund , and Guggenheim Partners , a financial services firm .

relation: no_relation (id: 098f665fb9317e68e0b2)
Subject: ['Dylan', 'Avery']
Object: ['Truth', 'Movement']
Jason Bermas The Mr. Smithers of the Truth Movement , Bermas is a loyal servant to Dylan Avery .

It's interesting to observe how the model confuses org:subsidiaries and org:parents

- - - 
### Focus on the family of relations relative date of foundation/dissolution of an organisation.

These are:
- `org:founded`
- `org:dissolved`

Note that the latter appears only once in the testing set, so claiming that it has bad F1 would be unwise given the limited number of examples. On the contrary, founded is quite good.

In [71]:
summary_relation_FN(test_data, "org:founded", summary_data)

Number of sentences with relation org:founded : 37
Number of sentences with wrong relation org:founded : 30
Of those sentences, 0 have long distance between entities

Summary of relations assigned instead of org:founded:
predicted
no_relation    30
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:founded wrongly predicted
predicted: no_relation (id: 098f63858279daf1ef91)
Subject: ['New', 'Fabris']
Object: ['1947']
Founded in 1947 by two brothers , Eugene and Quentin Fabris , New Fabris started out making sewing machine parts , before branching out into the auto sector , employing up to 800 workers in the 1990s .

predicted: no_relation (id: 098f63858251ac14afd5)
Subject: ['National', 'Congress', 'of', 'American', 'Indians']
Object: ['1944']
The National Congress of American Indians was founded in 1944 in response to assimilation policies being imposed on tribes by the federal government .

predicted: no_relation (id: 098f638582fd45e6cd93)
Subject: ['UASR']
Object: ['1989']
UASR was founded in 1989 by Mousa abu Mazook < http://wwwinvestigativeprojectorg/profile/106 > , who currently serves as the Deputy Chief of the HAMAS political bureau in Damascus , Syria , and has been listed as a Specially Designated Global Terrorist by the US government in 1995 .

predicted: no_relation (id: 098f63858219ab1ad8e8)
Subject: ['Countrywide']
Object: ['1969']
The Securities and Exchange Commission scheduled a news conference Thursday in Washington , DC , to discuss the allegations against Mozilo , who founded Countrywide in 1969 and was its chief executive until Bank of America purchased it last year as its financial condition deteriorated .

predicted: no_relation (id: 098f6385823cf1465a31)
Subject: ['MEF']
Object: ['1991']
MEF , which was founded in 1991 , has grabbed 15 medals -- five golds , five silvers and five bronzes -- from the international competitions since 1998 .

predicted: no_relation (id: 098f63858280e4611338)
Subject: ['National', 'Restaurant', 'Association']
Object: ['1919']
Founded in 1919 , the National Restaurant Association is the leading business association for the restaurant industry , which comprises 945,000 restaurant and food service outlets and a work force of nearly 13 million employees .

predicted: no_relation (id: 098f638582e4d868196e)
Subject: ['OANA']
Object: ['1961']
The OANA was formed in 1961 on the initiative of UNESCO to secure direct and free exchange of news between the news agencies of a region with more than half of the world 's population .

predicted: no_relation (id: 098f638582cefb0475d6)
Subject: ['Professional', 'Ski', 'Instructors', 'of', 'America']
Object: ['1961']
-LRB- End optional trim -RRB- The Professional Ski Instructors of America was founded in 1961 .

predicted: no_relation (id: 098f6385829ab87bd5c5)
Subject: ['China', 'Charity', 'Federation']
Object: ['1994']
Founded in 1994 , China Charity Federation and its branches at various levels have received more than 6 billion yuan -LRB- 0.8 US dollars -RRB- in donation .

predicted: no_relation (id: 098f665fb995cf5ba9fa)
Subject: ['CCF']
Object: ['1994']
CCF was established in 1994 .

predicted: no_relation (id: 098f6385825e1cafcd4c)
Subject: ['ALICO']
Object: ['1921']
Founded in 1921 , ALICO has 12,500 employees in more than 50 countries and 20 million customers worldwide .

predicted: no_relation (id: 098f63858214f3420ba7)
Subject: ['Asia', 'and', 'Pacific', 'region']
Object: ['December', '1961']
Formed in December 1961 , OANA now has 40 members in 33 countries in the Asia and Pacific region .

predicted: no_relation (id: 098f6385824eacec35bc)
Subject: ['ACSE']
Object: ['1992']
Founded in 1992 in Schaumburg , Illinois , the ACSE is one of the largest Chinese - American associations of professionals in the United States .

predicted: no_relation (id: 098f6385823e963e046e)
Subject: ['Hellen', 'Keller', 'International']
Object: ['1915']
Hellen Keller International was founded in 1915 and runs programs in 21 countries in Africa and Asia , as well as in the United States .

predicted: no_relation (id: 098f6385822dec1ca5fb)
Subject: ['ALICO']
Object: ['1921']
MetLife to acquire life insurance unit from AIG for 155 billion dollars Founded in 1921 , ALICO is a leading international life insurer that operates in more than 50 countries , providing consumers and businesses with products and services for life insurance , accident and health insurance , retirement and wealth management solutions .

predicted: no_relation (id: 098f665fb9fad86f3e0e)
Subject: ['Sycamore']
Object: ['1998']
The pair founded Sycamore in 1998 and took it public a year later with an astounding valuation of $ 14.4 billion .

predicted: no_relation (id: 098f6385829c97b83d3d)
Subject: ['NCCCC']
Object: ['1998']
The Chinese government set up special institutions to deal with climate change in 1990 , and established the National Coordination Committee on Climate Change -LRB- NCCCC -RRB- in 1998 .

predicted: no_relation (id: 098f6385820b0d2885b0)
Subject: ['It']
Object: ['1996']
KAMPALA , July 1 -LRB- Xinhua -RRB- It started in 1996 but expanded its activities over the next several years .

predicted: no_relation (id: 098f665fb9af28548c0b)
Subject: ['Alessi']
Object: ['1921']
Alessi was founded in 1921 , and store shelves hold a history of familiar household items , such as the Dr. Skud fly swatter -LRB- $ 16 -RRB- by French design superstar Philippe Starck .

predicted: no_relation (id: 098f638582532cd2609a)
Subject: ['Menil', 'Collection']
Object: ['1981']
When she announced the creation of the Menil Collection in 1981 , she infused fresh light and initiatives to the constants of scholarship , collecting and humanist enterprises at the heart of the foundation .

predicted: no_relation (id: 098f63858267ee5ad128)
Subject: ['UASR']
Object: ['1989']
UASR was founded in 1989 by Mousa abu Mazook < http://www.investigativeproject.org/profile/106 > , who currently serves as the Deputy Chief of the HAMAS political bureau in Damascus , Syria , and has been listed as a Specially Designated Global Terrorist by the US government in 1995 .

predicted: no_relation (id: 098f638582408181b421)
Subject: ['Zirh']
Object: ['1995']
New York-based Zirh was founded in 1995 and makes products using natural oils and extracts .

predicted: no_relation (id: 098f638582bcc27c4d85)
Subject: ['OANA']
Object: ['1961']
Founded in 1961 , the OANA groups 41 news agencies of 33 countries seeking to facilitate the free flow of information and cooperation between agencies in the region .

predicted: no_relation (id: 098f665fb9800598f57f)
Subject: ['OANA']
Object: ['1961']
OANA , which meets every three years , was set up in 1961 with the sponsorship of the UN cultural agency UNESCO to promote the exchange of news among national agencies in the region .

predicted: no_relation (id: 098f63858256a41a4b57)
Subject: ['Qatalys', ',', 'Inc']
Object: ['1995']
· Singapore/Australian Citizens and valid US H1-B visa holders are eligible Alen Smith <alen2sm@gmailcom> Software Developer Position Hi , com Direct : 972-782-9217 / 972-432-2890 * 201 Fax : 214-630-1481 Qatalys , Inc founded in 1995 and headquartered in Dallas , Texas with multiple offshore facilities in India .

predicted: no_relation (id: 098f638582f2d602779d)
Subject: ['OANA']
Object: ['1961']
The OANA was formed in 1961 on the initiative of UNESCO to secure direct and free exchange of news between the news agencies of a region inhabited by more than one half of the world 's population .

predicted: no_relation (id: 098f63858293a1e53ac2)
Subject: ['Pluribus']
Object: ['2009']
Pluribus , founded in 2009 , is a private equity company while Guggenheim is a privately held financial services firm managing more than 100 billion dollars in assets .

predicted: no_relation (id: 098f63858298b14b1553)
Subject: ['New', 'Fabris']
Object: ['1947']
Chatellerault , France , July 13 , 2009 -LRB- AFP -RRB- Founded in 1947 by two brothers , Eugene and Quentin Fabris , New Fabris started out making sewing machine parts , before branching out into the auto sector , employing up to 800 workers in the 1990s .

predicted: no_relation (id: 098f638582ec19d9e284)
Subject: ['The', 'orchestra']
Object: ['1945']
BEIJING , Oct 29 -LRB- Xinhua -RRB- The orchestra was founded in 1945 with Professor Tsai Chih-kue as its first president .

predicted: no_relation (id: 098f63858265643b5c70)
Subject: ['High', 'Point', 'Church']
Object: ['2000']
The 5,000-member High Point Church was founded in 2000 by Simons and his wife , April , whose brother is Joel Osteen , well-known pastor of the 38,000-member Lakewood Church in Houston .

In [72]:
summary_relation_FP(test_data, "org:founded", summary_data)

Number of sentences where the model predicts relation org:founded : 16
Number of sentences where the model outputs org:founded but the true one is a different one: 9
Of those sentences, 0 have long distance between entities

Summary of true relations to which org:founded is wrongly assigned:
relation
no_relation    9
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:founded assigned wrongly
relation: no_relation (id: 098f665fb9cb453c0c7c)
Subject: ['Pacific', 'Asia', 'Travel', 'Association']
Object: ['Tuesday']
More than 230 tourism executives , government officials and analysts attended the Pacific Asia Travel Association meeting Tuesday and Wednesday , billed as the region 's first to seek practical solutions to climate change .

relation: no_relation (id: 098f665fb9d5639d7619)
Subject: ['Menil', 'Collection']
Object: ['1986']
Since his Menil Collection building opened in Houston in 1986 , Piano 's use of light has inspired fervent admiration .

relation: no_relation (id: 098f665fb9e94d5e2eac)
Subject: ['Corporate', 'Library']
Object: ['2008']
The company 's director pay was ranked 56th out of 3,096 companies surveyed by the Corporate Library in 2008 , said Greg Ruel , a research associate at the organization .

relation: no_relation (id: 098f665fb9a8d286f3a7)
Subject: ['National', 'Restaurant', 'Association']
Object: ['recently']
A National Restaurant Association survey of chefs recently found 60 percent said Latin American cuisine is hot , behind only fusion cuisine in the ethnic food category .

relation: no_relation (id: 098f665fb99a4a28d321)
Subject: ['Pacific', 'Asia', 'Travel', 'Association']
Object: ['Wednesday']
More than 230 tourism executives , government officials and analysts attended the Pacific Asia Travel Association meeting Tuesday and Wednesday , billed as the region 's first to seek practical solutions to climate change .

relation: no_relation (id: 098f665fb9f7210bce9a)
Subject: ['ShopperTrak']
Object: ['Christmas']
ShopperTrak reported Wednesday that retail sales for Christmas week dropped 4.1 percent compared with a year ago , while foot traffic fell 6.8 percent .

relation: no_relation (id: 098f665fb9588c835b50)
Subject: ['AAUW']
Object: ['1913']
The AAUW started studying the disparity in 1913 , documenting different pay for men and women among federal government workers .

relation: no_relation (id: 098f665fb98147cee892)
Subject: ['Menil', 'Collection']
Object: ['1981']
Snow was born in Manhattan in 1981 to a family whose cultural contributions included the Menil Collection in Houston and the Dia Center for the Arts in Manhattan and Beacon , N.Y. .

relation: no_relation (id: 098f665fb9dff2971014)
Subject: ['Countrywide']
Object: ['late', 'July']
In a conference call with analysts and investors in late July , Kevin Bartlett , Countrywide 's chief investment officer , counted about 2,000 loan modifications done in June .

In [26]:
summary_relation_FN(test_data, "org:dissolved", summary_data)

Number of sentences with relation org:dissolved : 1
Number of sentences with wrong relation org:dissolved : 1
Of those sentences, 0 have long distance between entities

Summary of relations assigned instead of org:dissolved:
no_relation    1
Name: predicted, dtype: int64

List of (NOT LONG) sentences with relation org:dissolved wrongly predicted
predicted: no_relation (id: 098f6aee5e82b98e0308)
Subject: ['New', 'Fabris']
Object: ['June', '16']
New Fabris closed down June 16 .

In [25]:
summary_relation_FP(test_data, "org:dissolved", summary_data)

Number of sentences where the model predicts relation org:dissolved : 0
Number of sentences where the model outputs org:dissolved but the true one is a different one: 0
Of those sentences, 0 have long distance between entities

Summary of true relations to which org:dissolved is wrongly assigned:
Series([], Name: relation, dtype: int64)

List of (NOT LONG) sentences with relation org:dissolved assigned wrongly