# Relation-specific error analysis.
This notebook focuses on identifying errors which are specific to some relations.

Moreover, we investigate whether the model can correctly identify the correct relation out of those which may be similar. To identify these groups we use relations which are pointed out as similar in the annotation guidelines (including inverse relations like `org:founded` and `org:founded_by`), along with the understanding of the language. 

The analysis on some of the most interesting groups is reported, as including all of them would be challenging (all 42 relations!)

As a summary of the observed insights we noticed that:
- Majority of misclassifications involve some relations being wrongly classified as `no_relation` or the opposite occuring.
- There are some errors which are caused by wrong subject or object type. For example some `org` are assigned `pos`, so the model is unable to correctly identify the relations.

In [1]:
import pandas as pd
import json
import os, sys
import numpy as np
import matplotlib.pyplot as plt

from utils import scorer

In [2]:
def print_sentence_relation_subj_obj(data, print_text="predicted"):
    for i, sentence in enumerate(data["token"]):
        print(f"{print_text}: {data.iloc[i][print_text]} (id: {data.iloc[i]['id']})")
        print(
            f"Subject: {data.iloc[i]['token'][data.iloc[i]['subj_start']:data.iloc[i]['subj_end']+1]}"
        )
        print(
            f"Object: {data.iloc[i]['token'][data.iloc[i]['obj_start']:data.iloc[i]['obj_end']+1]}"
        )
        print(f"{' '.join(sentence)}\n")

In [3]:
def summary_relation_FN(dataset, relation, summary_data, not_long=True):
    """
    Given a dataset and a relation, it outputs the sentences where that relation is the correct one and the predicted one is wrong (i.e. TP and FN for that relation).
    It provides some summaries (number of wrong relations, predicted relations, number of sentences with long distance between entities).
    Afterwards, it prints the sentences along with the entities and the predicted relations.
    If not_long is True, it only prints the sentences where the distance between entities is NOT long
    """
    data_relation = test_data[dataset["relation"] == relation]
    print(f"Number of sentences with relation {relation} : {len(data_relation)}")

    data_relation_wrong = data_relation[
        data_relation["relation"] != data_relation["predicted"]
    ]
    print(
        f"Number of sentences with wrong relation {relation} : {len(data_relation_wrong)}"
    )

    data_relation_wrong_not_long = data_relation_wrong[
        data_relation_wrong["entity_distance_categorical"] != "long"
    ]
    print(
        f"Of those sentences, {len(data_relation_wrong) - len(data_relation_wrong_not_long)} have long distance between entities"
    )

    wrong_relations_summary = data_relation_wrong["predicted"].value_counts()
    print(
        f"\nSummary of relations assigned instead of {relation}:\n{wrong_relations_summary}\n"
    )

    print(f"List of (NOT LONG) sentences with relation {relation} wrongly predicted")
    print_sentence_relation_subj_obj(
        data_relation_wrong_not_long if not_long else data_relation_wrong,
        print_text="predicted",
    )

In [4]:
def summary_relation_FP(dataset, relation, summary_data, not_long=True):
    """
    Given a dataset and a relation, it outputs the sentences the model outputs the relation while the correct one is different (i.e. TP and FP for that relation).
    It provides some summaries (number of wrong relations, predicted relations, number of sentences with long distance between entities).
    Afterwards, it prints the sentences along with the entities and the predicted relations.
    If not_long is True, it only prints the sentences where the distance between entities is NOT long
    """
    data_relation = test_data[dataset["predicted"] == relation]
    print(
        f"Number of sentences where the model predicts relation {relation} : {len(data_relation)}"
    )

    data_relation_wrong = data_relation[data_relation["relation"] != relation]
    print(
        f"Number of sentences where the model outputs {relation} but the true one is a different one: {len(data_relation_wrong)}"
    )

    data_relation_wrong_not_long = data_relation_wrong[
        data_relation_wrong["entity_distance_categorical"] != "long"
    ]
    print(
        f"Of those sentences, {len(data_relation_wrong) - len(data_relation_wrong_not_long)} have long distance between entities"
    )

    wrong_relations_summary = data_relation_wrong["relation"].value_counts()
    print(
        f"\nSummary of true relations to which {relation} is wrongly assigned:\n{wrong_relations_summary}\n"
    )

    print(f"List of (NOT LONG) sentences with relation {relation} assigned wrongly")
    print_sentence_relation_subj_obj(
        data_relation_wrong_not_long if not_long else data_relation_wrong,
        print_text="relation",
    )

Read the data

In [5]:
tacrev_results = pd.read_csv("./evaluation/errors_TACREV_model.txt", sep="\t")
summary_data = scorer.score(
    tacrev_results["Gold Label"],
    tacrev_results["Prediction"],
    verbose=True,
    return_data=True,
).rename(
    columns={
        "F1": "Tacred_F1",
        "Precision": "Tacred_precision",
        "Recall": "Tacred_recall",
    }
)
summary_data.rename(
    columns={
        "Relation": "relation",
        "Tacred_precision": "Tacrev_precision",
        "Tacred_recall": "Tacrev_recall",
        "Tacred_F1": "Tacrev_F1",
    },
    inplace=True,
)

Per-relation statistics:
org:alternate_names                  P:  95.98%  R:  87.76%  F1:  91.68%  #: 245
org:city_of_headquarters             P:  82.98%  R:  87.64%  F1:  85.25%  #: 89
org:country_of_headquarters          P:  91.43%  R:  34.78%  F1:  50.39%  #: 92
org:dissolved                        P: 100.00%  R:   0.00%  F1:   0.00%  #: 1
org:founded                          P:  86.84%  R:  89.19%  F1:  88.00%  #: 37
org:founded_by                       P:  80.56%  R:  38.16%  F1:  51.79%  #: 76
org:member_of                        P: 100.00%  R:   0.00%  F1:   0.00%  #: 4
org:members                          P:   0.00%  R:   0.00%  F1:   0.00%  #: 16
org:number_of_employees/members      P: 100.00%  R:  42.86%  F1:  60.00%  #: 14
org:parents                          P:  32.00%  R:  14.04%  F1:  19.51%  #: 57
org:political/religious_affiliation  P:  28.00%  R:  70.00%  F1:  40.00%  #: 10
org:shareholders                     P:   0.00%  R:   0.00%  F1:   0.00%  #: 3
org:stateorprovince_of_headquarters  P:  74.51%  R:  74.51%  F1:  74.51%  #: 51
org:subsidiaries                     P:  48.65%  R:  58.06%  F1:  52.94%  #: 31
org:top_members/employees            P:  69.65%  R:  91.67%  F1:  79.16%  #: 348
org:website                          P:  59.46%  R:  81.48%  F1:  68.75%  #: 27
per:age                              P:  79.18%  R:  96.52%  F1:  87.00%  #: 201
per:alternate_names                  P:  33.33%  R: 100.00%  F1:  50.00%  #: 1
per:cause_of_death                   P:  63.33%  R:  40.43%  F1:  49.35%  #: 47
per:charges                          P:  68.66%  R:  86.79%  F1:  76.67%  #: 106
per:children                         P:  22.33%  R:  58.97%  F1:  32.39%  #: 39
per:cities_of_residence              P:  54.00%  R:  62.31%  F1:  57.86%  #: 130
per:city_of_birth                    P:  33.33%  R:  50.00%  F1:  40.00%  #: 6
per:city_of_death                    P:  36.36%  R:  50.00%  F1:  42.11%  #: 16
per:countries_of_residence           P:  72.97%  R:  20.77%  F1:  32.34%  #: 130
per:country_of_death                 P: 100.00%  R:   0.00%  F1:   0.00%  #: 10
per:date_of_birth                    P:  66.67%  R:  85.71%  F1:  75.00%  #: 7
per:date_of_death                    P:  39.73%  R:  69.05%  F1:  50.43%  #: 42
per:employee_of                      P:  69.14%  R:  66.67%  F1:  67.88%  #: 252
per:origin                           P:  58.57%  R:  73.87%  F1:  65.34%  #: 111
per:other_family                     P:  70.00%  R:  18.92%  F1:  29.79%  #: 37
per:parents                          P:  72.34%  R:  39.53%  F1:  51.13%  #: 86
per:religion                         P:  45.28%  R:  55.81%  F1:  50.00%  #: 43
per:schools_attended                 P:  93.33%  R:  45.16%  F1:  60.87%  #: 31
per:siblings                         P:  66.67%  R:  50.85%  F1:  57.69%  #: 59
per:spouse                           P:  42.06%  R:  80.30%  F1:  55.21%  #: 66
per:stateorprovince_of_birth         P:  66.67%  R:  85.71%  F1:  75.00%  #: 7
per:stateorprovince_of_death         P:  27.27%  R:  23.08%  F1:  25.00%  #: 13
per:stateorprovinces_of_residence    P:  68.09%  R:  43.84%  F1:  53.33%  #: 73
per:title                            P:  84.12%  R:  84.28%  F1:  84.20%  #: 509

In [6]:
with open("../../../data/tacred/json/train.json", "r") as file:
    data_train = json.load(file)
training_data = pd.json_normalize(data_train)

# Count occurrences of each relation in the training set and include them in the summary
relation_counts = training_data["relation"].value_counts()
train_counts_df = relation_counts.reset_index()
train_counts_df.rename(columns={"count": "train_counts"}, inplace=True)
summary_data = pd.merge(summary_data, train_counts_df)

In [7]:
with open("../../../data/tacrev/json/test.json", "r") as file:
    test_data = json.load(file)
test_data = pd.json_normalize(test_data)

In [8]:
test_data["predicted"] = tacrev_results["Prediction"]
test_data["entity_distance"] = [
    (test_data["subj_start"][i] - test_data["obj_end"][i])
    if test_data["subj_start"][i] > test_data["obj_end"][i]
    else (test_data["obj_start"][i] - test_data["subj_end"][i])
    for i in range(len(test_data))
]
q1_ed = test_data["entity_distance"].quantile(0.3333)
q2_ed = test_data["entity_distance"].quantile(0.6666)
test_data["entity_distance_categorical"] = [
    "short"
    if test_data["entity_distance"][i] < q1_ed
    else ["long" if test_data["entity_distance"][i] > q2_ed else "medium"][0]
    for i in range(len(test_data))
]

- - - 
## ORG: Relations
### Focus on the family of relations relative to membership and relations with other companies/organisations
From these family we consider these types of relations, as they are mentioned as  in the slot annotation guidelines.
- `org:member_of` and `org:member` (inverse relations)
- `org:parents` and `org:subsidiaries` (inverse relations)
- `org:shareholders`

First of all extract statistics for these relationships:\
We can see that some appear only a few times in the test set, so it would not be correct to draw general conclusions on the model performance on those. These include `org:member_of` and `org:shareholders`.

In [9]:
membership_relations = [
    "org:member_of",
    "org:members",
    "org:parents",
    "org:subsidiaries",
    "org:shareholders",
]
filtered_summary_data = summary_data[
    summary_data["relation"].isin(membership_relations)
].sort_values("Tacrev_F1", ascending=False)
filtered_summary_data

,relation,Tacrev_precision,Tacrev_recall,Tacrev_F1,test_counts,train_counts
13,org:subsidiaries,0.486486,0.580645,0.529412,31,278
9,org:parents,0.320000,0.140351,0.195122,57,268
6,org:member_of,1.000000,0.000000,0.000000,4,113
7,org:members,0.000000,0.000000,0.000000,16,155
11,org:shareholders,0.000000,0.000000,0.000000,3,70

Focus on relation: `org:members`\
First we consider instances where the true relation was `org:members` and a different relation was predicted while the second cell contains instances of other relations where `org:members` was predicted wrongly.

In [10]:
summary_relation_FN(test_data, "org:members", summary_data)

Number of sentences with relation org:members : 16
Number of sentences with wrong relation org:members : 16
Of those sentences, 9 have long distance between entities

Summary of relations assigned instead of org:members:
predicted
no_relation         14
org:subsidiaries     2
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:members wrongly predicted
predicted: no_relation (id: 098f6e00a8a07ffb432f)
Subject: ['Organization', 'of', 'Asia', '-', 'Pacific', 'News', 'Agencies']
Object: ['Azerbaijani', 'wire', 'service']
Trend , an Azerbaijani wire service , on Thursday became a full member of the Organization of Asia - Pacific News Agencies -LRB- OANA -RRB- .

predicted: no_relation (id: 098f6e00a8c213b31b91)
Subject: ['Pacific', 'Asia', 'Travel', 'Association']
Object: ['Taiwan']
The fair was organized by the Pacific Asia Travel Association , of which Taiwan is a senior member .

predicted: no_relation (id: 098f6e00a84925a504b7)
Subject: ['Central', 'American', 'Parliament']
Object: ['Panama']
Panama has submitted a letter of intention to quit the Central American Parliament -LRB- PARLACEN -RRB- , the foreign ministry said Wednesday .

predicted: org:subsidiaries (id: 098f6e00a8130bae6d80)
Subject: ['PATA']
Object: ['SAR', "'s", 'Tourist', 'Office']
MACAO , Sept 14 -LRB- Xinhua -RRB- The SAR 's Tourist Office is a member of PATA .

predicted: no_relation (id: 098f6e00a8875c6dfbbd)
Subject: ['OANA']
Object: ['AAP']
OANA members include , to name just a few , Australia 's AAP , China 's Xinhua , India 's PTI , Indonesia 's ANTARA , Iran 's IRNA , Japan 's Kyodo and Jiji Press , Pakistan 's PPI and APP , Kazakhstan 's Kazinform , Kuwait 's KUNA , Mongolia 's MONTSAME , the Philippines ' PNA , Russia 's Itar-Tass and RIA , Saudi Arabia 's SPA , the Republic of Korea 's Yonhap , and Turkey 's Anadolu .

predicted: org:subsidiaries (id: 098f6e00a8fdb802d661)
Subject: ['Central', 'American', 'Parliament']
Object: ['Panama']
Panama withdraws from Central American Parliament Its resolutions are not binding .

predicted: no_relation (id: 098f6e00a8af57214507)
Subject: ['OANA']
Object: ['Malaysian', 'National', 'News', 'Agency']
New media , including online news portals , blogs and social networking sites , were increasing their reach to the masses while traditional media particularly newspapers saw a decline in overall readership , said a paper presented to the assembly by the Malaysian National News Agency -LRB- BERNAMA -RRB- , an OANA member .

In [11]:
summary_relation_FP(test_data, "org:members", summary_data)

Number of sentences where the model predicts relation org:members : 2
Number of sentences where the model outputs org:members but the true one is a different one: 2
Of those sentences, 0 have long distance between entities

Summary of true relations to which org:members is wrongly assigned:
relation
no_relation         1
org:subsidiaries    1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:members assigned wrongly
relation: no_relation (id: 098f665fb973ab8f29c2)
Subject: ['Organisation', 'of', 'Asia-Pacific', 'News', 'Agencies']
Object: ['general', 'assembly']
Earlier this week Jakarta hosted the general assembly of the Organisation of Asia-Pacific News Agencies , during which Antara signed cooperation agreements with its Turkish and Azerbaijani counterparts .

relation: org:subsidiaries (id: 098f665fb9ff389142c6)
Subject: ['Organisation', 'of', 'Asia-Pacific', 'News', 'Agencies']
Object: ['general', 'assembly']
The general assembly of the Organisation of Asia-Pacific News Agencies -LRB- OANA -RRB- is seeking to boost the quality of the 40 news agencies across 33 countries that comprise it , said incoming OANA head and chief of Indonesia 's state-run Antara news agency Ahmad Mukhlis Yusuf .

It appears that the model tends to predict `org:subsidiaries` rather than the correct `org:member_of`. In all other cases the model predicts `no_relation` which appears to be the most common error.

Now we move to the other two members of this group of relations, i.e. `org:subsidiaries` and afterwards `org:parents`

In [12]:
summary_relation_FN(test_data, "org:subsidiaries", summary_data)

Number of sentences with relation org:subsidiaries : 31
Number of sentences with wrong relation org:subsidiaries : 13
Of those sentences, 3 have long distance between entities

Summary of relations assigned instead of org:subsidiaries:
predicted
no_relation    10
org:parents     2
org:members     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:subsidiaries wrongly predicted
predicted: org:members (id: 098f665fb9ff389142c6)
Subject: ['Organisation', 'of', 'Asia-Pacific', 'News', 'Agencies']
Object: ['general', 'assembly']
The general assembly of the Organisation of Asia-Pacific News Agencies -LRB- OANA -RRB- is seeking to boost the quality of the 40 news agencies across 33 countries that comprise it , said incoming OANA head and chief of Indonesia 's state-run Antara news agency Ahmad Mukhlis Yusuf .

predicted: no_relation (id: 098f6c74c5248883a246)
Subject: ['Nuclear', 'Decommissioning', 'Authority']
Object: ['Sellafield']
The consortium , Nuclear Management Partners Ltd. , signed a five - year contract to run the nuclear waste facility , with an option to extend it for another 12 years , according to the government 's Nuclear Decommissioning Authority , which owns Sellafield .

predicted: no_relation (id: 098f6c74c5144a3688f3)
Subject: ['Countrywide', 'Financial']
Object: ['IndyMac']
One of the banks identified is Countrywide Financial , the former parent company of IndyMac .

predicted: no_relation (id: 098f6c74c53079649f85)
Subject: ['Tribeca', 'Enterprises']
Object: ['Tribeca', 'Film', 'Festival']
Redford said promoting Cooper to festival director was an easy decision after predecessor Geoff Gilmore departed last year for Tribeca Enterprises , which runs Robert De Niro 's Tribeca Film Festival .

predicted: no_relation (id: 098f6c74c5868da27545)
Subject: ['TPI']
Object: ['TPI', 'Polene']
He keeps busy as a director of cement maker TPI Polene , a former unit of TPI .

predicted: no_relation (id: 098f6a9e36bd512d6303)
Subject: ['Tribeca', 'Enterprises']
Object: ['Tribeca']
A new distribution company , Tribeca Film , founded by the festival 's parent company Tribeca Enterprises , will make a dozen films -- including Whitecross ' directorial debut `` sex & drugs & rock & roll '' -- available on TV via video-on-demand in some 40 million homes .

predicted: no_relation (id: 098f6c74c51734f50e17)
Subject: ['AFP']
Object: ['Western', 'Regional', 'Bureau']
ADL falsely charges that I have `` a long-standing affiliation with American Free Press -LRB- AFP -RRB- , an anti-Semitic conspiracy-oriented newspaper.Pike is an AFP staff member , having served on its Western Regional Bureau .

predicted: no_relation (id: 098f6c74c54ba0ce1b97)
Subject: ['Countrywide', 'Financial']
Object: ['Countrywide', 'Securities']
The defendants in the Federal Home Loan Bank case were among the biggest sellers of mortgage-backed securities back in the day ; among those named are Deutsche Bank ; Bear Stearns ; Countrywide Securities , a division of Countrywide Financial ; Credit Suisse Securities ; and Merrill Lynch .

predicted: no_relation (id: 098f6c74c5d0d0361c68)
Subject: ['PDA']
Object: ['PDA', 'Virginia']
PDA Virginia is leading a national PDA campaign to pass HR 508 or similar legislation to expedite our withdrawal and begin a new diplomatic approach that can improve our safety and restore respect to the US .

predicted: org:parents (id: 098f6c74c51d0732d3bd)
Subject: ['Semen', 'Gresik']
Object: ['Semen', 'Padang']
However , the government let the deal expire in December 2001 amid protests from local politicians and workers at a Semen Gresik unit , Semen Padang in West Sumatra .

In [13]:
summary_relation_FP(test_data, "org:subsidiaries", summary_data)

Number of sentences where the model predicts relation org:subsidiaries : 37
Number of sentences where the model outputs org:subsidiaries but the true one is a different one: 19
Of those sentences, 2 have long distance between entities

Summary of true relations to which org:subsidiaries is wrongly assigned:
relation
no_relation      11
org:parents       5
org:members       2
org:member_of     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:subsidiaries assigned wrongly
relation: no_relation (id: 098f665fb9519aeaeb31)
Subject: ['Corporate', 'Library']
Object: ['Bank', 'of', 'America']
Paul Hodgson , research associate at the Corporate Library , a corporate governance research firm , criticized Bank of America for agreeing to the terms of Sambol 's exit deal .

relation: org:member_of (id: 098f6784e78abd5c3e0c)
Subject: ['ALICO']
Object: ['AIG']
ALICO , a member company of AIG is looking for one J2EE developer to help with a significant re-engineering project .

relation: no_relation (id: 098f665fb9db8801a68e)
Subject: ['Pluribus', 'Capital', 'Management']
Object: ['Global', 'Media', 'LLC']
In all , Nielsen is selling eight titles to e5 Global Media LLC , a new company formed by private equity firm Pluribus Capital Management , and Guggenheim Partners , a financial services company .

relation: no_relation (id: 098f665fb96de26a5585)
Subject: ['ALICO']
Object: ['AIA']
AIG , which was saved from bankruptcy by the US government in September 2008 , announced last month it was selling AIA to Prudential and another unit , ALICO , to US rival MetLife to pay back a huge chunk of its government bailout .

relation: no_relation (id: 098f665fb9d400954e89)
Subject: ['Pacific', 'Asia', 'Travel', 'Association']
Object: ['Burj', 'Al', 'Arab', 'Hotel']
Yen -- an emeritus chairman of the Taiwan Visitors ' Association who is known for having successfully rejuvenated the Grand Hotel , which used to be the jewel in the crown of Taiwan 's tourist hotels before falling into mediocrity -- recently invited Alwin Zecha , the younger brother of the owner of the seven-star Burj Al Arab Hotel and two-term chairman of the Pacific Asia Travel Association , to visit the eastern county of Taitung .

relation: no_relation (id: 098f665fb9223e7b5d62)
Subject: ['National', 'Taiwan', 'Symphony', 'Orchestra']
Object: ['Concert', 'Hall']
Six finalists will compete in the 2007 NTSO Piano Concerto Competition 's final round Dec. 8 at the National Taiwan Symphony Orchestra 's Concert Hall in Wufeng township , Taichung County .

relation: org:members (id: 098f6e00a8130bae6d80)
Subject: ['PATA']
Object: ['SAR', "'s", 'Tourist', 'Office']
MACAO , Sept 14 -LRB- Xinhua -RRB- The SAR 's Tourist Office is a member of PATA .

relation: org:parents (id: 098f6f706026a5989562)
Subject: ['ALICO']
Object: ['Federal', 'Reserve', 'Bank']
AIG said it had transferred ownership to the Federal Reserve Bank of parts of two subsidiaries , ALICO which is active in life assurance in the United States and AIA which provides life assurance abroad .

relation: no_relation (id: 098f665fb9b9a7e20bcf)
Subject: ['Countrywide']
Object: ['Bank', 'of', 'America']
In August , when US mortgage-related woes started to roil financial markets in the United States and other industrialized countries , Bank of America bought a 16 percent stake in Countrywide in a deal worth two billion dollars .

relation: no_relation (id: 098f665fb9d9b154bdb6)
Subject: ['National', 'Restaurant', 'Association']
Object: ['Conserve', 'Solutions', 'Center']
Besides the Green Restaurant Association 's 800 square-foot presence in the South Hall , the National Restaurant Association also has its own sustainability-related Conserve Solutions Center .

relation: org:parents (id: 098f665fb928f7437e01)
Subject: ['ALICO']
Object: ['American', 'International', 'Group']
US life insurance giant MetLife said on Monday it will acquire American International Group unit American Life Insurance company -LRB- ALICO -RRB- in a deal worth 15.5 billion dollars .

relation: org:members (id: 098f6e00a8fdb802d661)
Subject: ['Central', 'American', 'Parliament']
Object: ['Panama']
Panama withdraws from Central American Parliament Its resolutions are not binding .

relation: org:parents (id: 098f6c74c58f11662010)
Subject: ['ALICO']
Object: ['AIG']
ALERT ¥ MetLife says it acquires AIG unit ALICO for 155 billion dollars

relation: no_relation (id: 098f665fb9ac8bf60430)
Subject: ['National', 'Restaurant', 'Association']
Object: ['Multicultural', 'Foodservice', 'and', 'Hospitality', 'Alliance']
`` This is not a new issue , '' said Gerald A. Fernandez , the president of the Multicultural Foodservice and Hospitality Alliance and a director of the National Restaurant Association .

relation: no_relation (id: 098f665fb9ca7cb522fc)
Subject: ['PATA']
Object: ['SAR', "'s", 'Tourist', 'Office']
The SAR 's Tourist Office is a member of PATA .

relation: org:parents (id: 098f6f7060d93a4ce2ad)
Subject: ['ALICO']
Object: ['AIG']
AIA and ALICO would remain wholly owned subsidiaries of AIG , and the insurance giant would continue to operate them .

relation: org:parents (id: 098f6c74c55313d8127b)
Subject: ['ALICO']
Object: ['American', 'International', 'Group']
US life insurance giant MetLife said on Monday it will acquire American International Group unit American Life Insurance company -LRB- ALICO -RRB- in a deal worth 155 billion dollars .

A similar behaviour is observed, in this case it appears that in many intances, the errors are due to the relations `org:subsidiaries` and `org:parents` are misclassified by swapping one with the other; note that these two relations are one the reverse of the other.


> Also note that in sentence (098f6c74c51d0732d3bd) the model appears to be correct, while the label appears to be wrong.

predicted: `org:parents` (id: 098f6c74c51d0732d3bd)\
label: `org:subsidiaries`\
Subject: ['Semen', 'Gresik']\
Object: ['Semen', 'Padang']\
However , the government let the deal expire in December 2001 amid protests from local politicians and workers at a Semen Gresik unit , Semen Padang in West Sumatra .

This points to some errors still being present in the dataset, as only part of it was revisited.

It appears that as expected on most instances the model either wrongly assigns no relation to sentences where the relation is of a different type or vice-versa it assigns the specific relation on no relation instances.

Whenever the error is due to a specific sentence, it mixes relations which are all (or almost) within the same group as defined above.

- - - 
### Focus on the family of relations relative to location of headquarters of a company.

These are:
- `org:city_of_headquarters`
- `org:country_of_headquarters`
- `org:stateorprovince_of_headquarters`

On these the model on average achieves a quite high precision and recall, with a smaller recall on `org:country_of_headquarters`.

In [14]:
membership_relations = [
    "org:city_of_headquarters",
    "org:country_of_headquarters",
    "org:stateorprovince_of_headquarters",
]
filtered_summary_data = summary_data[
    summary_data["relation"].isin(membership_relations)
].sort_values("Tacrev_F1", ascending=False)
filtered_summary_data

,relation,Tacrev_precision,Tacrev_recall,Tacrev_F1,test_counts,train_counts
1,org:city_of_headquarters,0.829787,0.876404,0.852459,89,357
12,org:stateorprovince_of_headquarters,0.745098,0.745098,0.745098,51,221
2,org:country_of_headquarters,0.914286,0.347826,0.503937,92,438

In [15]:
summary_relation_FN(test_data, "org:city_of_headquarters", summary_data)

Number of sentences with relation org:city_of_headquarters : 89
Number of sentences with wrong relation org:city_of_headquarters : 11
Of those sentences, 1 have long distance between entities

Summary of relations assigned instead of org:city_of_headquarters:
predicted
no_relation                10
per:cities_of_residence     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:city_of_headquarters wrongly predicted
predicted: no_relation (id: 098f65158dde1a8effc2)
Subject: ['Greenberg', 'Smoked', 'Turkey']
Object: ['Tyler']
TURKEY-VENDOR -LRB- Tyler , Texas -RRB- -- By the time Sam Greenberg closes Greenberg Smoked Turkey in Tyler for the holiday season on Dec 24 and hands each of his 200 employees a free bird , more than 200,000 turkeys will have emerged from the company 's 20 brick-lined , hardwood-fired pit houses .

predicted: no_relation (id: 098f65158d7ae6af12ee)
Subject: ['Countrywide']
Object: ['Calabasas']
Continued 1 | 2 | 3 Next > Calabasas , California-based Countrywide also said it had funded $ 344 billion of mortgage loans in August , the fewest this year and down 173 percent from a year earlier , as it tightened lending standards .

predicted: no_relation (id: 098f65158dbac1d6fb52)
Subject: ['Koch', 'Foods']
Object: ['Chicago']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant and at Koch Foods Inc. 's Chicago area headquarters , said Brian Moskowitz , a special agent for ICE enforcement .

predicted: per:cities_of_residence (id: 098f60af8f4f637db90f)
Subject: ['Sycamore']
Object: ['Chelmsford']
Sycamore , a Chelmsford company that makes optical-networking equipment , is just one company among more than 200 struggling to investigate and ultimately explain evidence the dates on stock option awards were altered or otherwise rigged to make the perks more valuable .

predicted: no_relation (id: 098f60af8f27f7e91410)
Subject: ['Sycamore']
Object: ['Chelmsford']
The Securities and Exchange Commission also charged Sycamore , a maker of telecommunications equipment in Chelmsford , with financial reporting violations , including making false and misleading statements related to the options .

predicted: no_relation (id: 098f65158de33b68af0c)
Subject: ['Koch', 'Foods']
Object: ['Chicago']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant and at Koch Foods Inc. 's Chicago area headquarters , said Brian Moskowitz , a special agent in charge of ICE enforcement for Ohio and Michigan .

predicted: no_relation (id: 098f65158d9d5809f9e0)
Subject: ['ShopperTrak']
Object: ['Chicago']
National retail sales fell 58 percent for the week ending Aug 29 , according to a report by Chicago retail analyst ShopperTrak .

predicted: no_relation (id: 098f65158d347d960ec3)
Subject: ['ShopperTrak']
Object: ['Chicago']
But in January , lower revenue is better than a rack full of clothes , said Bill Martin , co-founder and executive vice president of ShopperTrak , a Chicago company that follows consumer shopping habits .

predicted: no_relation (id: 098f65158dd4a1339ba1)
Subject: ['ShopperTrak']
Object: ['Chicago']
National retail sales fell 5.8 percent for the week ending Aug. 29 , according to a report by Chicago retail analyst ShopperTrak .

predicted: no_relation (id: 098f65158db736b6e3a0)
Subject: ['American', 'Free', 'Press']
Object: ['D.C.']
Readers can reprint and are free to redistribute - as long as full credit is given to American Free Press - 645 Pennsylvania Avenue SE , Suite 100 Washington , D.C. 20003

We note something interesting from the output above. Consider sentence with id 098f60af8f4f637db90f, where the model assigns relationship `per:cities_of_residence`, which appears very different from the true relation of `org:city_of_headquarters`.

Subject: [Sycamore]\
Object: [Chelmsford]\
**Sycamore** , a **Chelmsford** company that makes optical-networking equipment , is just one company among more than 200 struggling to investigate and ultimately explain evidence the dates on stock option awards were altered or otherwise rigged to make the perks more valuable .

However this appears to be caused by the fact in the test set, the entity Sycamore is wrongly assigned subject type `PER`, while it is clearly an organisation.

In [16]:
summary_relation_FN(test_data, "org:country_of_headquarters", summary_data)

Number of sentences with relation org:country_of_headquarters : 92
Number of sentences with wrong relation org:country_of_headquarters : 60
Of those sentences, 28 have long distance between entities

Summary of relations assigned instead of org:country_of_headquarters:
predicted
no_relation    56
per:origin      4
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:country_of_headquarters wrongly predicted
predicted: no_relation (id: 098f6179d3bb2b93c59d)
Subject: ['Countrywide', 'Financial']
Object: ['US']
An optimistic outlook from troubled US mortgage giant Countrywide Financial on Friday , coupled with expectations for a US rate cut on Wednesday , raised hopes that the fallout from the US housing woes is easing , dealers said .

predicted: no_relation (id: 098f6179d38875ffc221)
Subject: ['National', 'Congress', 'of', 'American', 'Indians']
Object: ['Washington', ',', 'DC']
Iroquois passport dispute raises sovereignty issue The National Congress of American Indians , based in Washington , DC , has advocated on behalf of the lacrosse team , urging British officials to allow the members entry into England on their Iroquois-issued passports .

predicted: per:origin (id: 098f6379356a57b0663a)
Subject: ['Alessi']
Object: ['Italian']
Alberto Alessi , president of the Italian design firm Alessi , will speak Nov. 18 at the museum about the role his family 's business has played in bringing creative and functional design to the world market .

predicted: no_relation (id: 098f6179d3aaaf5f1981)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
The center monitored the donations received by the government 's civil affairs departments , the country 's two major charity groups , the Red Cross Society of China and China Charity Federation , and about 1,850 charity foundations .

predicted: no_relation (id: 098f6179d3c87d6551cb)
Subject: ['NTSO']
Object: ['Taiwan']
The 2007 International Music Festival organized by National Taiwan Symphony Orchestra -LRB- NTSO -RRB- will begin Oct. 6 in Taichung City in central Taiwan , an NTSO spokesman said Tuesday .

predicted: no_relation (id: 098f6179d3356c7ac439)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
A deep-rooted concept among wealthy individuals in China is to leave their entire fortunes to their descendants , which might be a major obstacle preventing donations to charity , according to Zhang Yinjun , spokesperson with one of China 's largest charity organization , the China Charity Federation .

predicted: no_relation (id: 098f6179d32568701b63)
Subject: ['National', 'Energy', 'Administration']
Object: ['China']
He is widely seen in the West as China 's top policymaker on energy because he heads the country 's National Energy Administration .

predicted: no_relation (id: 098f6784e76428a36fa3)
Subject: ['NDRC']
Object: ['China']
China 's National Development and Reform Commission -LRB- NDRC -RRB- on July 1 released a tape recording as evidence of the traders ' mung bean price manipulation .

predicted: no_relation (id: 098f6179d3c4e8dd5a28)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
This was in addition to 462 houses funded by the Chinese Red Cross Society , the China Charity Federation , the Macao Red Cross and other non-governmental organizations in China .

predicted: no_relation (id: 098f6f318b0d6bce68a8)
Subject: ['Air', 'Evac', 'EMS', ',', 'Inc']
Object: ['United', 'States']
Air Evac Lifeteam is operated by Air Evac EMS , Inc , the largest independently owned air medical service provider in the United States , which conducts its operations through 90 mutually - supporting air medical bases across 14 states .

predicted: no_relation (id: 098f6179d353ea584a95)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
In 2006 , she was awarded the title of China Charity Ambassador by the China Charity Federation .

predicted: no_relation (id: 098f6179d3b262dba3c9)
Subject: ['National', 'Taiwan', 'Symphony', 'Orchestra']
Object: ['Taiwan']
The 2007 International Music Festival organized by National Taiwan Symphony Orchestra -LRB- NTSO -RRB- will begin Oct. 6 in Taichung City in central Taiwan , an NTSO spokesman said Tuesday .

predicted: no_relation (id: 098f6179d344d9b197ce)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
The Dalian Wanda Group Co. Ltd. based in northeast China 's Liaoning Province donated 10 million yuan to Zhouqu Monday through the China Charity Federation .

predicted: no_relation (id: 098f6179d3360a19d991)
Subject: ['Myanmar', 'Equestrian', 'Federation']
Object: ['Myanmar']
The Baron 's Cup 2010 horse racing event , co-organized by the Myanmar Equestrian Federation -LRB- MEF -RRB- and Myanmar Brewery Ltd , will be held this month to boost the country 's equestrian sport , according to the MEF Friday .

predicted: no_relation (id: 098f6179d332576fa12a)
Subject: ['New', 'Fabris']
Object: ['France']
French official dismisses threat by former workers Anne Frackowiak , top aide to the local governor in Chatellerault , 305 kilometers -LRB- 190 miles -RRB- southwest of Paris , said Monday the former New Fabris factory workers will be meeting with France 's industry minister to discuss their demand for euro 30,000 -LRB- $ 41,000 -RRB- compensation each by the end of the month .

predicted: no_relation (id: 098f6179d38c414673de)
Subject: ['Australian', 'Defence', 'Force']
Object: ['Australia']
-- Afghan refugees attempting to climb aboard inflatable rescue boats after their boat burst into flames northwest of Australia last April were allegedly kicked and fended off by Australian Defence Force members .

predicted: per:origin (id: 098f665fb9cf874c333b)
Subject: ['Alessi']
Object: ['Italian']
Johnson praises the Boston shakers - the style of cocktail shaker in which a tempered pint glass is inverted into a slightly larger metal cup - made by the Italian firm Alessi .

predicted: no_relation (id: 098f6179d3d390c391e1)
Subject: ['National', 'Development', 'and', 'Reform', 'Commission']
Object: ['China']
China 's top economic planning agency , the National Development and Reform Commission -LRB- NDRC -RRB- , released the country 's first mid - and long-term grain security plan here on Thursday .

predicted: no_relation (id: 098f6179d391d587bab7)
Subject: ['NTSO']
Object: ['Taiwan']
The 2007 International Music Festival organized by National Taiwan Symphony Orchestra -LRB- NTSO -RRB- will begin Oct. 6 in Taichung City in central Taiwan , an NTSO spokesman said Tuesday .

predicted: no_relation (id: 098f665fb997e65bb4b9)
Subject: ['Alessi']
Object: ['Italian']
Cynthia Roberto , who works at Alessi , the Italian design company , said she agreed because `` I was 36 , and I did n't want to waste time figuring out if he 's the one . ''

predicted: no_relation (id: 098f665fb985cb7420c8)
Subject: ['Countrywide', 'Financial', 'Corp.']
Object: ['U.S.']
Angelo Mozilo , chief executive of Countrywide Financial Corp. , the No. 1 U.S. mortgage lender , said he supports those efforts , which have been backed by congressional Democrats but opposed by the Bush administration .

predicted: no_relation (id: 098f6179d332466b594f)
Subject: ['NDRC']
Object: ['China']
China 's National Development and Reform Commission -LRB- NDRC -RRB- , the country 's top economic planner , said Friday that corn imports will help curb soaring corn prices .

predicted: no_relation (id: 098f665fb914bf09e4ae)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
A deep-rooted concept among wealthy individuals in China is to leave their entire fortunes to their descendants , which might be a major obstacle to charities attracting donations , according to Zhang Yinjun , spokesperson with one of China 's largest charity organization , the China Charity Federation .

predicted: no_relation (id: 098f6179d3bf65adce30)
Subject: ['National', 'Energy', 'Administration']
Object: ['China']
Zhang Yuqing , an official with China 's National Energy Administration , said China is willing to learn advanced technologies of exploring gas .

predicted: no_relation (id: 098f6179d3af303209dc)
Subject: ['Koch', 'Foods']
Object: ['U.S.']
U.S. Immigration and Customs Enforcement agents seized documents and other materials at the Koch Foods plant and at Koch Foods Inc. 's Chicago area headquarters , said Brian Moskowitz , a special agent in charge of ICE enforcement for Ohio and Michigan .

predicted: no_relation (id: 098f665fb9071329f7a8)
Subject: ['NDRC']
Object: ['China']
The National Development and Reform Commission -LRB- NDRC -RRB- , China 's economic planner , confirmed with Xinhua Friday that it had granted a confirmation letter to Geely , allowing the company to conduct takeover talks with Volvo .

predicted: no_relation (id: 098f6f318b94ca896204)
Subject: ['Sushi', 'Ran']
Object: ['United', 'States']
The event , described by organisers as `` the Oscars of the sushi world '' , was won last year by Mitsunori Kusakabe of the Sushi Ran restaurant in California , United States .

predicted: no_relation (id: 098f6179d37993f82429)
Subject: ['NDA']
Object: ['Britain']
Westinghouse said it was in `` advanced discussions '' with Britain 's Nuclear Decommissioning Authority -LRB- NDA -RRB- about taking on a long-term management lease for the site at Springfields near Preston .

predicted: no_relation (id: 098f6179d3720e0d034a)
Subject: ['China', 'Charity', 'Federation']
Object: ['China']
Ministry official Pang Chenmin made the announcement at a press conference here on Friday where officials from the Red Cross of China and the China Charity Federation explained the distribution of donations for earthquake-hit areas in southwest China .

predicted: no_relation (id: 098f6179d310848de30c)
Subject: ['The', 'factory']
Object: ['France']
CHATELLERAULT , France 2009-07-13 18:38:34 UTC French official dismisses threat by former workers The factory 's more than 350 workers were fired last month .

predicted: per:origin (id: 098f665fb9b35c9a666b)
Subject: ['Alessi']
Object: ['Italian']
Alessi , an Italian company , is known for witty versions of everyday objects , from bottle openers to pasta cookers , designed by more than 200 noted architects and designers .

predicted: per:origin (id: 098f665fb9a723cc5d01)
Subject: ['Alessi']
Object: ['Italian']
A design project involving the National Palace Museum -LRB- NPM -RRB- and the Italian design company Alessi , which purports to represent a `` third culture '' of East meeting West , was launched Wednesday .

Also in the sentence with id 098f6379356a57b0663a, a similar error is observed.

Subject: ['Alessi']\
Object: ['Italian']\
Alberto Alessi , president of the **Italian** design firm **Alessi** , will speak Nov. 18 at the museum about the role his family 's business has played in bringing creative and functional design to the world market .

Also here, the error appears to be caused by the fact that the company Alessi has associated subject type `PER`, instead of the correct one which should be `ORG`.

In [17]:
summary_relation_FP(test_data, "org:city_of_headquarters", summary_data)

Number of sentences where the model predicts relation org:city_of_headquarters : 94
Number of sentences where the model outputs org:city_of_headquarters but the true one is a different one: 16
Of those sentences, 4 have long distance between entities

Summary of true relations to which org:city_of_headquarters is wrongly assigned:
relation
no_relation                            15
org:stateorprovince_of_headquarters     1
Name: count, dtype: int64

List of (NOT LONG) sentences with relation org:city_of_headquarters assigned wrongly
relation: no_relation (id: 098f665fb9089e6ebb71)
Subject: ['Norris', 'Church', 'Mailer']
Object: ['Brooklyn']
Mailer resided in Provincetown , Massachusetts , with his wife of 33 years , Norris Church Mailer , and maintained an apartment in Brooklyn , New York .

relation: org:stateorprovince_of_headquarters (id: 098f65158d567ded4b2a)
Subject: ['National', 'Congress', 'of', 'American', 'Indians']
Object: ['D.C.']
The National Congress of American Indians , based in Washington , D.C. , has advocated on behalf of the lacrosse team , urging British officials to allow the members entry into England on their Iroquois-issued passports .

relation: no_relation (id: 098f665fb95e2a7eb06b)
Subject: ['Semen', 'Gresik']
Object: ['JAKARTA']
JAKARTA : Indonesian shares hit a new high , led by cement maker Semen Gresik and heavy equipment company United Tractors .

relation: no_relation (id: 098f665fb99e2a12bd23)
Subject: ['Organisation', 'of', 'Asia-Pacific', 'News', 'Agencies']
Object: ['Jakarta']
Earlier this week Jakarta hosted the general assembly of the Organisation of Asia-Pacific News Agencies , during which Antara signed cooperation agreements with its Turkish and Azerbaijani counterparts .

relation: no_relation (id: 098f665fb90dd422e3ae)
Subject: ['Menil', 'Collection']
Object: ['Houston']
09.14.07 - Bernice Berend Rose , a director of drawings and special exhibitions at the PaceWildenstein Gallery in New York and earlier a longtime curator at the Museum of Modern Art , has been named chief curator of the Menil Collection 's new Drawings Institute in Houston .

relation: no_relation (id: 098f665fb99ee71ebe4b)
Subject: ['PATA']
Object: ['Hangzhou']
Shao Qiwei , director of China National Tourism Administration , said domestic tourists would top 1.9 billion this year , a year - on-year rise of 10 percent , at a recent awarding ceremony of Pacific-Asia Travel Association -LRB- PATA -RRB- held in Hangzhou , capital of east China 's Zhejiang Province .

relation: no_relation (id: 098f665fb9f7d4078beb)
Subject: ['Koch', 'Foods']
Object: ['Wichita']
Koch Foods is not affiliated with Wichita , Kansas,-based Koch Industries , the largest private company in the United States , a spokeswoman for Koch Industries said .

relation: no_relation (id: 098f665fb9075d6f2ece)
Subject: ['American', 'Free', 'Press']
Object: ['Chicago']
Christopher Bollyn is a much-traveled international journalist currently based in Chicago , serving as Midwest bureau chief for American Free Press .

relation: no_relation (id: 098f665fb9c4ff1ae385)
Subject: ['Arlo', 'Looking', 'Cloud']
Object: ['Oglala', 'Lakota']
One man , Arlo Looking Cloud , an Oglala Lakota , and a member of AIM , is serving life in prison for her murder while his accomplice , the man he accused of pulling the trigger , John `` Boy '' Graham , a native of the Yukon in Canada , is awaiting extradition to the United States to stand trial .

relation: no_relation (id: 098f665fb9cf0a08a1df)
Subject: ['National', 'Congress', 'of', 'American', 'Indians']
Object: ['Niagara', 'Falls']
Perrelli faced skepticism from listeners at a National Congress of American Indians conference in Niagara Falls , N.Y. , recently , several of whom pressed for specific action rather than another `` listening session , '' a tactic tried by administrations going back to Jimmy Carter .

relation: no_relation (id: 098f665fb98d7cba2ec3)
Subject: ['National', 'Urban', 'League']
Object: ['New', 'Orleans']
`` The dropout rate is driving the nation 's increasing prison population , and it 's a drag on America 's economic competitiveness , '' said Marc H. Morial , the former New Orleans mayor who is president of the National Urban League , one of the groups in the coalition that commissioned the report .

relation: no_relation (id: 098f665fb949f1f9ba08)
Subject: ['American', 'Association', 'of', 'University', 'Women']
Object: ['Detroit']
Margaret Garritsen was born in Detroit and graduated from the University of Michigan as an American Association of University Women scholar , and she was elected to Phi Beta Kappa .

Finally, a similar array of issues arise when D.C. is the object of some relation. 

Consider for example the sentence with id 098f65158d567ded4b2a where the correct relation is `org:stateorprovince_of_headquarters`, while the model predicts `org:city_of_headquarters`.

Subject: ['National', 'Congress', 'of', 'American', 'Indians']\
Object: ['D.C.']\
The **National Congress of American Indians** , based in Washington , **D.C.** , has advocated on behalf of the lacrosse team , urging British officials to allow the members entry into England on their Iroquois-issued passports .

The reason appears to be that D.C. is assigned the object type `LOCATION`, rather than the more specific ones which are available like `STATE` (the correct one) or `CITY`. Due to the masking performed by the model, the model only has the object type to perform the prediction, and as such it has no way to reconstruct whether it is a city or a state.